if pc . count_item ( 30202 ) < 1 then 
say_title ( mob_name ( npc . get_race ( ) ) .. ":" ) 
say ( ) 
say ( translate . tanaka_event . _120_say ) 
say ( ) 
else 
say_title ( mob_name ( npc . get_race ( ) ) .. ":" ) 
say ( ) 
say ( translate . tanaka_event . _130_say ) 
say ( ) 
say_reward ( translate . tanaka_event . _140_sayReward ) 
if select ( translate . locale . yes , translate . locale . no ) == 1 then 
local Reward = { 
[ 1 ] = { 71081 , 3 } , 
[ 2 ] = { 71082 , 3 } , 
[ 3 ] = { 55009 , 1 } , 
[ 4 ] = { 85013 , 1 } , 
[ 5 ] = { 78022 , 1 } , 
[ 6 ] = { 78023 , 1 } , 
[ 7 ] = { 71052 , 1 } , 
[ 8 ] = { 70063 , 1 } , 
[ 9 ] = { 27990 , 3 } , 
[ 10 ] = { 51505 , 1 } , 
[ 11 ] = { 76020 , 1 } , 
[ 12 ] = { 85000 , 3 } , 
[ 13 ] = { 71051 , 3 } , 
[ 14 ] = { 55001 , 1 } , 
[ 15 ] = { 79504 , 1 } , 
} 
local item = math . random ( 1 , 15 ) 
pc . remove_item ( 30202 , 1 ) 
pc . give_item2 ( Reward [ item ] [ 1 ] , Reward [ item ] [ 2 ] ) 
end 
end 
