[package]
name = "db"
version = "0.1.0"
edition = "2021"
description = "Metin2 database layer"

[dependencies]
tokio = { workspace = true }
futures-util = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
common = { path = "../common" }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"

[lints]
workspace = true
