//! SQL-free conversion of the active legacy renewal-shop boot table.
//!
//! The legacy `InitializeShopEXTable` loader in
//! `server/server/db/ClientManagerBoot.cpp` uses one generated 28-column
//! query.  It groups rows in a `std::map<int, TShopTable*>` and copies each
//! joined row into the current item slot.  This module is the corresponding
//! pure projection boundary.  It does not execute SQL, own a connection,
//! choose a boot feature profile, or mutate process/game state.
//!
//! The strict decoder is the default.  It requires complete decimal numeric
//! cells and rejects SQL `NULL`, source errors, numeric overflow, and malformed
//! rows.  [`decode_renewal_shop_query_row_legacy`] is the explicit compatibility
//! decoder.  It models the active x86 `str_to_number` calls, including C
//! whitespace, signs, decimal prefixes, x86 destination casts, embedded-NUL
//! termination, and the fact that NULL/empty/first-NUL input leaves an existing
//! destination unchanged.
//!
//! The legacy source allocates a new `TShopTable`, immediately `memset`s all
//! of its bytes to zero, and then parses into that state.  Consequently a
//! renewal item has zero `pos` and `price_type` unless the query explicitly
//! overwrites them.  This differs from the base-shop constructor defaults.
//! A row with a zero item vnum still writes every supplied field into the
//! current slot, but it does not advance `byItemCount`; a later row can
//! overwrite that same slot.  A NULL/empty item-vnum cell leaves the current
//! vnum unchanged in the legacy policy.  The builder rejects writes once the
//! fixed 40-slot capacity is exhausted instead of reproducing an overrun.
//!
//! Names are copied as raw bytes with the source's fixed 33-byte `memcpy`.
//! A NULL name is a typed error (the legacy pointer dereference is not a safe
//! policy).  For a short raw cell, the unavailable tail is zero-filled; this
//! is the documented safe representation of the legacy over-read.  Embedded
//! NUL bytes are preserved rather than interpreted as a C string.
//!
//! An empty query result is valid and produces an empty
//! `BootSectionKind::RenewalShop` section with the fixed record width.

use std::collections::BTreeMap;
use std::error::Error;
use std::fmt;

use protocol::db_boot::{BootSection, BootSectionKind};
use protocol::db_records::{
    RecordCodec, ShopItemAttribute, ShopItemRecord, ShopTableRecord, SHOP_HOST_ITEM_MAX_NUM,
    SHOP_ITEM_ATTRIBUTE_MAX_NUM, SHOP_ITEM_SOCKET_MAX_NUM,
};

/// Exact statement generated by the legacy `InitializeShopEXTable` query.
///
/// The spaces before the attribute commas and before `FROM` are source
/// spelling and are retained for byte-for-byte query compatibility.
pub const RENEWAL_SHOP_TABLE_QUERY: &str = "SELECT shopex.vnum, shopex.name, shopex.npc_vnum, shopex_item.item_vnum, shopex_item.count, shopex_item.price, shopex_item.price_vnum, shopex_item.price_type+0, socket0, socket1, socket2, socket3, socket4, socket5, attrtype0, attrvalue0 , attrtype1, attrvalue1 , attrtype2, attrvalue2 , attrtype3, attrvalue3 , attrtype4, attrvalue4 , attrtype5, attrvalue5 , attrtype6, attrvalue6 FROM shopex LEFT JOIN shopex_item ON shopex.vnum = shopex_item.shop_vnum ORDER BY shopex.vnum, shopex_item.item_vnum";

/// Short alias for [`RENEWAL_SHOP_TABLE_QUERY`].
pub const RENEWAL_SHOP_QUERY: &str = RENEWAL_SHOP_TABLE_QUERY;

/// Compatibility alias using the legacy `shopex` spelling.
pub const SHOPEX_TABLE_QUERY: &str = RENEWAL_SHOP_TABLE_QUERY;

/// Number of columns promised by the generated query.
pub const RENEWAL_SHOP_TABLE_QUERY_COLUMNS: usize = 28;

/// Alias for [`RENEWAL_SHOP_TABLE_QUERY_COLUMNS`].
pub const RENEWAL_SHOP_QUERY_COLUMN_COUNT: usize = RENEWAL_SHOP_TABLE_QUERY_COLUMNS;

/// Fixed source capacity of one renewal shop.
pub const RENEWAL_SHOP_ITEM_MAX_NUM: usize = SHOP_HOST_ITEM_MAX_NUM;

/// Alias matching the legacy C++ constant name.
pub const SHOP_HOST_ITEM_MAX_NUM_RENEWAL: usize = RENEWAL_SHOP_ITEM_MAX_NUM;

/// Number of bytes in `szShopName`, including its NUL.
pub const RENEWAL_SHOP_NAME_BYTES: usize = 33;

/// Alias for the source `SHOP_TAB_NAME_MAX + 1` width.
pub const RENEWAL_SHOP_TABLE_NAME_BYTES: usize = RENEWAL_SHOP_NAME_BYTES;

/// Exact packed item width in the active x86 build.
pub const RENEWAL_SHOP_ITEM_WIRE_SIZE: usize = ShopItemRecord::WIRE_SIZE;

/// Exact packed renewal-shop width in the active x86 build.
pub const RENEWAL_SHOP_TABLE_WIRE_SIZE: usize = ShopTableRecord::WIRE_SIZE;

/// Section record-size field used by the renewal boot stream.
#[allow(clippy::cast_possible_truncation)]
pub const RENEWAL_SHOP_SECTION_RECORD_SIZE: u16 = RENEWAL_SHOP_TABLE_WIRE_SIZE as u16;

/// Maximum distinct shops representable by the boot `u16` count.
pub const RENEWAL_SHOP_TABLE_MAX_RECORDS: usize = u16::MAX as usize;

/// Maximum section-data length at the representable `u16` count.
pub const RENEWAL_SHOP_TABLE_MAX_SECTION_BYTES: usize =
    RENEWAL_SHOP_TABLE_WIRE_SIZE * RENEWAL_SHOP_TABLE_MAX_RECORDS;

/// A defensive global source-row ceiling.  Repeated zero-vnum rows are legal
/// source behavior, so this is intentionally a global ceiling rather than a
/// per-shop `40 * groups` claim.
pub const RENEWAL_SHOP_TABLE_MAX_SOURCE_ROWS: usize =
    RENEWAL_SHOP_TABLE_MAX_RECORDS * RENEWAL_SHOP_ITEM_MAX_NUM;

/// Return a source-row ceiling for a configured distinct-shop limit.
///
/// This helper is advisory for acquisition adapters.  It does not reject
/// repeated zero-vnum rows when a smaller caller limit is selected; the pure
/// builder applies its fixed-capacity check independently.
#[must_use]
pub const fn renewal_shop_source_row_limit(max_records: usize) -> Option<usize> {
    if max_records > RENEWAL_SHOP_TABLE_MAX_RECORDS {
        None
    } else {
        Some(max_records * RENEWAL_SHOP_ITEM_MAX_NUM)
    }
}

/// Exact query column names/expressions in source order.
pub const RENEWAL_SHOP_TABLE_QUERY_COLUMN_NAMES: [&str; RENEWAL_SHOP_TABLE_QUERY_COLUMNS] = [
    "shopex.vnum",
    "shopex.name",
    "shopex.npc_vnum",
    "shopex_item.item_vnum",
    "shopex_item.count",
    "shopex_item.price",
    "shopex_item.price_vnum",
    "shopex_item.price_type+0",
    "socket0",
    "socket1",
    "socket2",
    "socket3",
    "socket4",
    "socket5",
    "attrtype0",
    "attrvalue0",
    "attrtype1",
    "attrvalue1",
    "attrtype2",
    "attrvalue2",
    "attrtype3",
    "attrvalue3",
    "attrtype4",
    "attrvalue4",
    "attrtype5",
    "attrvalue5",
    "attrtype6",
    "attrvalue6",
];

/// Return a stable query-column name for diagnostics.
#[must_use]
pub const fn renewal_shop_query_column_name(index: usize) -> &'static str {
    if index < RENEWAL_SHOP_TABLE_QUERY_COLUMN_NAMES.len() {
        RENEWAL_SHOP_TABLE_QUERY_COLUMN_NAMES[index]
    } else {
        "unknown"
    }
}

/// One raw value returned by a renewal-shop query adapter.
///
/// `Text` and `Bytes` are both non-NULL facts.  `Bytes` is lossless for
/// non-UTF-8 driver data and embedded NULs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RenewalShopQueryValue {
    /// A non-NULL textual SQL value.
    Text(String),
    /// A non-NULL raw SQL value.
    Bytes(Vec<u8>),
    /// A SQL `NULL` value.
    Null,
    /// An extraction or source error.
    Error(String),
}

impl RenewalShopQueryValue {
    /// Construct a non-NULL textual value.
    #[must_use]
    pub fn text(value: impl Into<String>) -> Self {
        Self::Text(value.into())
    }

    /// Copy a non-NULL raw value.
    #[must_use]
    pub fn bytes(value: impl AsRef<[u8]>) -> Self {
        Self::Bytes(value.as_ref().to_vec())
    }

    /// Construct SQL `NULL`.
    #[must_use]
    pub const fn null() -> Self {
        Self::Null
    }

    /// Construct a source error.
    #[must_use]
    pub fn error(message: impl Into<String>) -> Self {
        Self::Error(message.into())
    }
}

impl From<String> for RenewalShopQueryValue {
    fn from(value: String) -> Self {
        Self::Text(value)
    }
}

impl From<&str> for RenewalShopQueryValue {
    fn from(value: &str) -> Self {
        Self::Text(value.to_owned())
    }
}

impl From<Vec<u8>> for RenewalShopQueryValue {
    fn from(value: Vec<u8>) -> Self {
        Self::Bytes(value)
    }
}

impl From<&[u8]> for RenewalShopQueryValue {
    fn from(value: &[u8]) -> Self {
        Self::Bytes(value.to_vec())
    }
}

/// A source-shaped row for the fixed 28-column renewal query.
///
/// The vector retains malformed widths so conversion can return a typed
/// `ColumnCount` error instead of indexing past the supplied row.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RenewalShopQueryRow {
    columns: Vec<RenewalShopQueryValue>,
}

impl RenewalShopQueryRow {
    /// Construct a row while retaining all supplied cells and their order.
    pub fn new<I>(columns: I) -> Self
    where
        I: IntoIterator<Item = RenewalShopQueryValue>,
    {
        Self {
            columns: columns.into_iter().collect(),
        }
    }

    /// Alias for [`Self::new`].
    #[must_use]
    pub fn from_columns<I>(columns: I) -> Self
    where
        I: IntoIterator<Item = RenewalShopQueryValue>,
    {
        Self::new(columns)
    }

    /// Construct and validate a 28-column row.
    ///
    /// # Errors
    ///
    /// Returns [`RenewalShopRowError::ColumnCount`] when `columns` does not
    /// contain exactly [`RENEWAL_SHOP_TABLE_QUERY_COLUMNS`] cells.
    pub fn try_new<I>(columns: I) -> Result<Self, RenewalShopRowError>
    where
        I: IntoIterator<Item = RenewalShopQueryValue>,
    {
        let row = Self::new(columns);
        check_row_width(&row)?;
        Ok(row)
    }

    /// Construct from a statically sized column set.
    #[must_use]
    pub fn from_typed_columns(
        columns: [RenewalShopQueryValue; RENEWAL_SHOP_TABLE_QUERY_COLUMNS],
    ) -> Self {
        Self::new(columns)
    }

    /// Borrow all cells in source-query order.
    #[must_use]
    pub fn columns(&self) -> &[RenewalShopQueryValue] {
        &self.columns
    }

    /// Consume the row and return its cells.
    #[must_use]
    pub fn into_columns(self) -> Vec<RenewalShopQueryValue> {
        self.columns
    }

    /// Return the supplied width, including a malformed width.
    #[must_use]
    pub fn column_count(&self) -> usize {
        self.columns.len()
    }
}

impl From<[RenewalShopQueryValue; RENEWAL_SHOP_TABLE_QUERY_COLUMNS]> for RenewalShopQueryRow {
    fn from(columns: [RenewalShopQueryValue; RENEWAL_SHOP_TABLE_QUERY_COLUMNS]) -> Self {
        Self::from_typed_columns(columns)
    }
}

impl TryFrom<Vec<RenewalShopQueryValue>> for RenewalShopQueryRow {
    type Error = RenewalShopRowError;

    fn try_from(columns: Vec<RenewalShopQueryValue>) -> Result<Self, Self::Error> {
        Self::try_new(columns)
    }
}

/// Common aliases for query adapters and tests.
pub type RenewalShopTableQueryRow = RenewalShopQueryRow;
/// Alias for the raw renewal-shop query value.
pub type RenewalShopTableQueryValue = RenewalShopQueryValue;
/// Alias for one raw query column value.
pub type RenewalShopQueryColumn = RenewalShopQueryValue;
/// Alias for one raw renewal-shop table cell.
pub type RenewalShopTableCell = RenewalShopQueryValue;
/// Alias for a raw renewal-shop table row.
pub type RenewalShopTableRow = RenewalShopQueryRow;
/// Alias for the typed renewal-shop row error.
pub type RenewalShopTableRowError = RenewalShopRowError;
/// Alias for decoded renewal-shop row data.
pub type RenewalShopQueryRowData = DecodedRenewalShopRow;
/// Alias for decoded renewal-shop row data.
pub type RenewalShopDecodedRow = DecodedRenewalShopRow;
/// Alias for renewal-shop section limits.
pub type RenewalShopTableSectionLimits = RenewalShopSectionLimits;
/// Alias for renewal-shop section errors.
pub type RenewalShopTableSectionError = RenewalShopSectionError;
/// Alias for renewal-shop section build errors.
pub type RenewalShopTableSectionBuildError = RenewalShopSectionError;
/// Short alias for the SQL-free renewal-shop loader.
pub type RenewalShopLoader = RenewalShopTableLoader;
/// Short alias for the SQL-free renewal-shop loader error.
pub type RenewalShopLoadError<E> = RenewalShopTableLoadError<E>;

/// A typed error in one strict or legacy renewal-shop row.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RenewalShopRowError {
    /// The row did not contain exactly 28 cells.
    ColumnCount {
        /// Required source width.
        expected: usize,
        /// Supplied source width.
        actual: usize,
    },
    /// A required cell was SQL `NULL`.
    Null {
        /// Zero-based query column.
        column: usize,
    },
    /// A source adapter could not obtain or convert a cell.
    Source {
        /// Zero-based query column.
        column: usize,
        /// Original diagnostic.
        message: String,
    },
    /// A non-NULL value was not a complete strict decimal integer.
    InvalidNumber {
        /// Zero-based query column.
        column: usize,
        /// Bounded lossy diagnostic.
        value: String,
        /// Target integer type.
        target: &'static str,
    },
    /// A syntactically valid integer did not fit its strict target type.
    NumberOverflow {
        /// Zero-based query column.
        column: usize,
        /// Bounded lossy diagnostic.
        value: String,
        /// Target integer type.
        target: &'static str,
    },
}

impl fmt::Display for RenewalShopRowError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::ColumnCount { expected, actual } => write!(
                formatter,
                "renewal-shop query row has {actual} columns; expected {expected}"
            ),
            Self::Null { column } => write!(
                formatter,
                "renewal-shop query column {} is NULL",
                renewal_shop_query_column_name(*column)
            ),
            Self::Source { column, message } => write!(
                formatter,
                "renewal-shop query column {} could not be read: {}",
                renewal_shop_query_column_name(*column),
                bounded_display(message)
            ),
            Self::InvalidNumber {
                column,
                value,
                target,
            } => write!(
                formatter,
                "renewal-shop query column {} value {:?} is not a strict {}",
                renewal_shop_query_column_name(*column),
                value,
                target
            ),
            Self::NumberOverflow {
                column,
                value,
                target,
            } => write!(
                formatter,
                "renewal-shop query column {} value {:?} overflows {}",
                renewal_shop_query_column_name(*column),
                value,
                target
            ),
        }
    }
}

impl Error for RenewalShopRowError {}

/// Per-field writes produced by one decoded row.
///
/// `None` is meaningful in the legacy policy: `str_to_number` did not write
/// its destination because the cell was SQL NULL, empty, or began with NUL.
/// `Some(0)` is different: it explicitly overwrites the field with zero.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RenewalShopItemUpdate {
    /// Item vnum write.
    pub vnum: Option<u32>,
    /// Item count write.
    pub count: Option<u16>,
    /// Item price write (`ENABLE_REMOVE_LIMIT_GOLD` is active).
    pub price: Option<u64>,
    /// Price-item vnum write.
    pub price_vnum: Option<u32>,
    /// Price selector write.
    pub price_type: Option<u8>,
    /// Socket writes.
    pub sockets: [Option<i32>; SHOP_ITEM_SOCKET_MAX_NUM],
    /// Attribute writes, in source order.
    pub attrs: [RenewalShopAttributeUpdate; SHOP_ITEM_ATTRIBUTE_MAX_NUM],
}

/// One attribute pair's optional writes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RenewalShopAttributeUpdate {
    /// `bType` write.
    pub attr_type: Option<u8>,
    /// `sValue` write.
    pub value: Option<i16>,
}

impl RenewalShopAttributeUpdate {
    /// Construct two explicit writes.
    #[must_use]
    pub const fn new(attr_type: Option<u8>, value: Option<i16>) -> Self {
        Self { attr_type, value }
    }
}

impl RenewalShopItemUpdate {
    /// Construct an update with all fields explicitly written.
    #[must_use]
    pub fn written(
        vnum: u32,
        count: u16,
        price: u64,
        price_vnum: u32,
        price_type: u8,
        sockets: [i32; SHOP_ITEM_SOCKET_MAX_NUM],
        attrs: [ShopItemAttribute; SHOP_ITEM_ATTRIBUTE_MAX_NUM],
    ) -> Self {
        Self {
            vnum: Some(vnum),
            count: Some(count),
            price: Some(price),
            price_vnum: Some(price_vnum),
            price_type: Some(price_type),
            sockets: sockets.map(Some),
            attrs: attrs.map(|attr| {
                RenewalShopAttributeUpdate::new(Some(attr.attr_type), Some(attr.value))
            }),
        }
    }
}

/// Decoded logical values for one source row.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DecodedRenewalShopRow {
    /// Signed x86 map key.
    pub shop_vnum: i32,
    /// Raw fixed-width name copied for this row.
    pub shop_name: [u8; RENEWAL_SHOP_NAME_BYTES],
    /// Optional stateful NPC write.
    pub npc_vnum: Option<u32>,
    /// State-preserving writes into the current item slot.
    pub item: RenewalShopItemUpdate,
}

impl DecodedRenewalShopRow {
    /// Return the item-vnum write, if this row supplied one.
    #[must_use]
    pub fn item_vnum(&self) -> Option<u32> {
        self.item.vnum
    }
}

fn bounded_display(value: &str) -> String {
    const LIMIT: usize = 96;
    if value.chars().count() <= LIMIT {
        return value.to_owned();
    }
    let mut out = value.chars().take(LIMIT).collect::<String>();
    out.push('…');
    out
}

fn bounded_value(bytes: &[u8]) -> String {
    const LIMIT: usize = 96;
    let text = String::from_utf8_lossy(bytes);
    if text.chars().count() <= LIMIT {
        return text.into_owned();
    }
    let mut out = text.chars().take(LIMIT).collect::<String>();
    out.push('…');
    out
}

fn check_row_width(row: &RenewalShopQueryRow) -> Result<(), RenewalShopRowError> {
    let actual = row.column_count();
    if actual == RENEWAL_SHOP_TABLE_QUERY_COLUMNS {
        Ok(())
    } else {
        Err(RenewalShopRowError::ColumnCount {
            expected: RENEWAL_SHOP_TABLE_QUERY_COLUMNS,
            actual,
        })
    }
}

fn raw_cell_bytes(
    value: &RenewalShopQueryValue,
    column: usize,
) -> Result<&[u8], RenewalShopRowError> {
    match value {
        RenewalShopQueryValue::Text(text) => Ok(text.as_bytes()),
        RenewalShopQueryValue::Bytes(bytes) => Ok(bytes.as_slice()),
        RenewalShopQueryValue::Null => Err(RenewalShopRowError::Null { column }),
        RenewalShopQueryValue::Error(message) => Err(RenewalShopRowError::Source {
            column,
            message: message.clone(),
        }),
    }
}

fn copy_raw_name(
    value: &RenewalShopQueryValue,
    column: usize,
) -> Result<[u8; RENEWAL_SHOP_NAME_BYTES], RenewalShopRowError> {
    let bytes = raw_cell_bytes(value, column)?;
    let mut out = [0_u8; RENEWAL_SHOP_NAME_BYTES];
    let copy_len = bytes.len().min(RENEWAL_SHOP_NAME_BYTES);
    out[..copy_len].copy_from_slice(&bytes[..copy_len]);
    Ok(out)
}

fn strict_decimal_parts(
    bytes: &[u8],
    column: usize,
    target: &'static str,
    signed: bool,
) -> Result<(bool, u128), RenewalShopRowError> {
    if bytes.is_empty() || bytes[0] == 0 {
        return Err(RenewalShopRowError::InvalidNumber {
            column,
            value: bounded_value(bytes),
            target,
        });
    }
    let mut offset = 0;
    let mut negative = false;
    if signed {
        match bytes[0] {
            b'-' => {
                negative = true;
                offset = 1;
            }
            b'+' => {
                return Err(RenewalShopRowError::InvalidNumber {
                    column,
                    value: bounded_value(bytes),
                    target,
                });
            }
            _ => {}
        }
    }
    if offset == bytes.len() {
        return Err(RenewalShopRowError::InvalidNumber {
            column,
            value: bounded_value(bytes),
            target,
        });
    }
    let mut magnitude = 0_u128;
    for &byte in &bytes[offset..] {
        if byte == 0 || !byte.is_ascii_digit() {
            return Err(RenewalShopRowError::InvalidNumber {
                column,
                value: bounded_value(bytes),
                target,
            });
        }
        let digit = u128::from(byte - b'0');
        magnitude = match magnitude
            .checked_mul(10)
            .and_then(|value| value.checked_add(digit))
        {
            Some(value) => value,
            None => {
                return Err(RenewalShopRowError::NumberOverflow {
                    column,
                    value: bounded_value(bytes),
                    target,
                })
            }
        };
    }
    Ok((negative, magnitude))
}

#[allow(clippy::cast_possible_truncation)]
fn strict_i32(value: &RenewalShopQueryValue, column: usize) -> Result<i32, RenewalShopRowError> {
    let bytes = raw_cell_bytes(value, column)?;
    let (negative, magnitude) = strict_decimal_parts(bytes, column, "i32", true)?;
    let max = if negative {
        1_u128 << 31
    } else {
        (1_u128 << 31) - 1
    };
    if magnitude > max {
        return Err(RenewalShopRowError::NumberOverflow {
            column,
            value: bounded_value(bytes),
            target: "i32",
        });
    }
    if negative {
        if magnitude == (1_u128 << 31) {
            Ok(i32::MIN)
        } else {
            Ok(-(magnitude as i32))
        }
    } else {
        Ok(magnitude as i32)
    }
}

#[allow(clippy::cast_possible_truncation)]
fn strict_u32(value: &RenewalShopQueryValue, column: usize) -> Result<u32, RenewalShopRowError> {
    let bytes = raw_cell_bytes(value, column)?;
    let (negative, magnitude) = strict_decimal_parts(bytes, column, "u32", false)?;
    if negative || magnitude > u128::from(u32::MAX) {
        return Err(RenewalShopRowError::NumberOverflow {
            column,
            value: bounded_value(bytes),
            target: "u32",
        });
    }
    Ok(magnitude as u32)
}

#[allow(clippy::cast_possible_truncation)]
fn strict_u16(value: &RenewalShopQueryValue, column: usize) -> Result<u16, RenewalShopRowError> {
    let bytes = raw_cell_bytes(value, column)?;
    let (negative, magnitude) = strict_decimal_parts(bytes, column, "u16", false)?;
    if negative || magnitude > u128::from(u16::MAX) {
        return Err(RenewalShopRowError::NumberOverflow {
            column,
            value: bounded_value(bytes),
            target: "u16",
        });
    }
    Ok(magnitude as u16)
}

#[allow(clippy::cast_possible_truncation)]
fn strict_u8(value: &RenewalShopQueryValue, column: usize) -> Result<u8, RenewalShopRowError> {
    let bytes = raw_cell_bytes(value, column)?;
    let (negative, magnitude) = strict_decimal_parts(bytes, column, "u8", false)?;
    if negative || magnitude > u128::from(u8::MAX) {
        return Err(RenewalShopRowError::NumberOverflow {
            column,
            value: bounded_value(bytes),
            target: "u8",
        });
    }
    Ok(magnitude as u8)
}

#[allow(clippy::cast_possible_truncation)]
fn strict_i16(value: &RenewalShopQueryValue, column: usize) -> Result<i16, RenewalShopRowError> {
    let bytes = raw_cell_bytes(value, column)?;
    let (negative, magnitude) = strict_decimal_parts(bytes, column, "i16", true)?;
    let max = if negative {
        1_u128 << 15
    } else {
        (1_u128 << 15) - 1
    };
    if magnitude > max {
        return Err(RenewalShopRowError::NumberOverflow {
            column,
            value: bounded_value(bytes),
            target: "i16",
        });
    }
    if negative {
        if magnitude == (1_u128 << 15) {
            Ok(i16::MIN)
        } else {
            Ok(-(magnitude as i16))
        }
    } else {
        Ok(magnitude as i16)
    }
}

#[allow(clippy::cast_possible_truncation)]
fn strict_u64(value: &RenewalShopQueryValue, column: usize) -> Result<u64, RenewalShopRowError> {
    let bytes = raw_cell_bytes(value, column)?;
    let (negative, magnitude) = strict_decimal_parts(bytes, column, "u64", false)?;
    if negative || magnitude > u128::from(u64::MAX) {
        return Err(RenewalShopRowError::NumberOverflow {
            column,
            value: bounded_value(bytes),
            target: "u64",
        });
    }
    Ok(magnitude as u64)
}

fn is_c_whitespace(byte: u8) -> bool {
    matches!(byte, b' ' | b'\t' | b'\n' | 0x0b | 0x0c | b'\r')
}

#[derive(Debug, Clone, Copy)]
struct LegacyScan {
    negative: bool,
    has_digit: bool,
    magnitude: u128,
    saturated: bool,
}

fn scan_legacy_number(bytes: &[u8]) -> LegacyScan {
    let mut offset = 0;
    while offset < bytes.len() && is_c_whitespace(bytes[offset]) {
        offset += 1;
    }
    let mut negative = false;
    if offset < bytes.len() && (bytes[offset] == b'+' || bytes[offset] == b'-') {
        negative = bytes[offset] == b'-';
        offset += 1;
    }
    let mut magnitude = 0_u128;
    let mut saturated = false;
    let mut has_digit = false;
    while offset < bytes.len() {
        let byte = bytes[offset];
        if !byte.is_ascii_digit() {
            break;
        }
        has_digit = true;
        let digit = u128::from(byte - b'0');
        if !saturated {
            match magnitude
                .checked_mul(10)
                .and_then(|value| value.checked_add(digit))
            {
                Some(value) => magnitude = value,
                None => saturated = true,
            }
        }
        offset += 1;
    }
    LegacyScan {
        negative,
        has_digit,
        magnitude,
        saturated,
    }
}

#[allow(clippy::cast_possible_truncation)]
fn legacy_i32_from_bytes(bytes: &[u8]) -> i32 {
    let scan = scan_legacy_number(bytes);
    if !scan.has_digit {
        return 0;
    }
    let limit = 1_u128 << 31;
    if scan.saturated || scan.magnitude > limit {
        return if scan.negative { i32::MIN } else { i32::MAX };
    }
    if scan.negative {
        if scan.magnitude == limit {
            i32::MIN
        } else {
            -(scan.magnitude as i32)
        }
    } else {
        scan.magnitude as i32
    }
}

#[allow(clippy::cast_possible_truncation)]
fn legacy_u32_from_bytes(bytes: &[u8]) -> u32 {
    let scan = scan_legacy_number(bytes);
    if !scan.has_digit {
        return 0;
    }
    if scan.saturated || scan.magnitude > u128::from(u32::MAX) {
        return u32::MAX;
    }
    let magnitude = scan.magnitude as u32;
    if scan.negative {
        0_u32.wrapping_sub(magnitude)
    } else {
        magnitude
    }
}

#[allow(clippy::cast_possible_truncation)]
fn legacy_u64_from_bytes(bytes: &[u8]) -> u64 {
    let scan = scan_legacy_number(bytes);
    if !scan.has_digit {
        return 0;
    }
    if scan.saturated || scan.magnitude > u128::from(u64::MAX) {
        return u64::MAX;
    }
    let magnitude = scan.magnitude as u64;
    if scan.negative {
        0_u64.wrapping_sub(magnitude)
    } else {
        magnitude
    }
}

fn legacy_optional<T>(
    value: &RenewalShopQueryValue,
    column: usize,
    parse: fn(&[u8]) -> T,
) -> Result<Option<T>, RenewalShopRowError> {
    match value {
        RenewalShopQueryValue::Null => Ok(None),
        RenewalShopQueryValue::Error(message) => Err(RenewalShopRowError::Source {
            column,
            message: message.clone(),
        }),
        RenewalShopQueryValue::Text(text) => {
            let bytes = text.as_bytes();
            if bytes.is_empty() || bytes.first() == Some(&0) {
                Ok(None)
            } else {
                Ok(Some(parse(bytes)))
            }
        }
        RenewalShopQueryValue::Bytes(bytes) => {
            if bytes.is_empty() || bytes.first() == Some(&0) {
                Ok(None)
            } else {
                Ok(Some(parse(bytes)))
            }
        }
    }
}

fn legacy_optional_i32(
    value: &RenewalShopQueryValue,
    column: usize,
) -> Result<Option<i32>, RenewalShopRowError> {
    legacy_optional(value, column, legacy_i32_from_bytes)
}

fn legacy_optional_u32(
    value: &RenewalShopQueryValue,
    column: usize,
) -> Result<Option<u32>, RenewalShopRowError> {
    legacy_optional(value, column, legacy_u32_from_bytes)
}

#[allow(clippy::cast_possible_truncation)]
fn legacy_optional_u16(
    value: &RenewalShopQueryValue,
    column: usize,
) -> Result<Option<u16>, RenewalShopRowError> {
    legacy_optional(value, column, |bytes| legacy_u32_from_bytes(bytes) as u16)
}

#[allow(clippy::cast_possible_truncation)]
fn legacy_optional_u8(
    value: &RenewalShopQueryValue,
    column: usize,
) -> Result<Option<u8>, RenewalShopRowError> {
    legacy_optional(value, column, |bytes| legacy_u32_from_bytes(bytes) as u8)
}

#[allow(clippy::cast_possible_truncation)]
fn legacy_optional_i16(
    value: &RenewalShopQueryValue,
    column: usize,
) -> Result<Option<i16>, RenewalShopRowError> {
    legacy_optional(value, column, |bytes| legacy_i32_from_bytes(bytes) as i16)
}

fn legacy_optional_u64(
    value: &RenewalShopQueryValue,
    column: usize,
) -> Result<Option<u64>, RenewalShopRowError> {
    legacy_optional(value, column, legacy_u64_from_bytes)
}

fn strict_row_item(
    row: &RenewalShopQueryRow,
) -> Result<RenewalShopItemUpdate, RenewalShopRowError> {
    let columns = row.columns();
    // Keep conversion order aligned with InitializeShopEXTable's col++ walk.
    // This also makes the first typed error deterministic when several cells
    // are malformed.
    let vnum = strict_u32(&columns[3], 3)?;
    let count = strict_u16(&columns[4], 4)?;
    let price = strict_u64(&columns[5], 5)?;
    let price_vnum = strict_u32(&columns[6], 6)?;
    let price_type = strict_u8(&columns[7], 7)?;
    let sockets = [
        strict_i32(&columns[8], 8)?,
        strict_i32(&columns[9], 9)?,
        strict_i32(&columns[10], 10)?,
        strict_i32(&columns[11], 11)?,
        strict_i32(&columns[12], 12)?,
        strict_i32(&columns[13], 13)?,
    ];
    let mut attrs =
        [RenewalShopAttributeUpdate::new(Some(0), Some(0)); SHOP_ITEM_ATTRIBUTE_MAX_NUM];
    for (index, attribute) in attrs.iter_mut().enumerate() {
        let column = 14 + index * 2;
        *attribute = RenewalShopAttributeUpdate::new(
            Some(strict_u8(&columns[column], column)?),
            Some(strict_i16(&columns[column + 1], column + 1)?),
        );
    }
    Ok(RenewalShopItemUpdate {
        vnum: Some(vnum),
        count: Some(count),
        price: Some(price),
        price_vnum: Some(price_vnum),
        price_type: Some(price_type),
        sockets: sockets.map(Some),
        attrs,
    })
}

fn legacy_row_item(
    row: &RenewalShopQueryRow,
) -> Result<RenewalShopItemUpdate, RenewalShopRowError> {
    let columns = row.columns();
    // Preserve the source's scalar -> socket -> attribute read order.
    let vnum = legacy_optional_u32(&columns[3], 3)?;
    let count = legacy_optional_u16(&columns[4], 4)?;
    let price = legacy_optional_u64(&columns[5], 5)?;
    let price_vnum = legacy_optional_u32(&columns[6], 6)?;
    let price_type = legacy_optional_u8(&columns[7], 7)?;
    let sockets = [
        legacy_optional_i32(&columns[8], 8)?,
        legacy_optional_i32(&columns[9], 9)?,
        legacy_optional_i32(&columns[10], 10)?,
        legacy_optional_i32(&columns[11], 11)?,
        legacy_optional_i32(&columns[12], 12)?,
        legacy_optional_i32(&columns[13], 13)?,
    ];
    let mut attrs = [RenewalShopAttributeUpdate::new(None, None); SHOP_ITEM_ATTRIBUTE_MAX_NUM];
    for (index, attribute) in attrs.iter_mut().enumerate() {
        let column = 14 + index * 2;
        *attribute = RenewalShopAttributeUpdate::new(
            legacy_optional_u8(&columns[column], column)?,
            legacy_optional_i16(&columns[column + 1], column + 1)?,
        );
    }
    Ok(RenewalShopItemUpdate {
        vnum,
        count,
        price,
        price_vnum,
        price_type,
        sockets,
        attrs,
    })
}

/// A concrete item value materialized from a strict row or from a caller-made
/// update.  The builder uses [`RenewalShopItemUpdate`] instead, because legacy
/// NULL cells can omit individual writes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RenewalShopDecodedItem {
    /// Item vnum.
    pub vnum: u32,
    /// Item count.
    pub count: u16,
    /// Item price.
    pub price: u64,
    /// Price-item vnum.
    pub price_vnum: u32,
    /// Price selector; the source does not restrict its range.
    pub price_type: u8,
    /// Socket values.
    pub sockets: [i32; SHOP_ITEM_SOCKET_MAX_NUM],
    /// Attribute values.
    pub attrs: [ShopItemAttribute; SHOP_ITEM_ATTRIBUTE_MAX_NUM],
}

impl RenewalShopDecodedItem {
    /// Materialize an update over an all-zero renewal slot.
    #[must_use]
    pub fn from_update(update: &RenewalShopItemUpdate) -> Self {
        let mut sockets = [0_i32; SHOP_ITEM_SOCKET_MAX_NUM];
        for (slot, value) in sockets.iter_mut().zip(update.sockets) {
            *slot = value.unwrap_or(0);
        }
        let mut attrs = [ShopItemAttribute::default(); SHOP_ITEM_ATTRIBUTE_MAX_NUM];
        for (slot, update) in attrs.iter_mut().zip(update.attrs) {
            slot.attr_type = update.attr_type.unwrap_or(0);
            slot.value = update.value.unwrap_or(0);
        }
        Self {
            vnum: update.vnum.unwrap_or(0),
            count: update.count.unwrap_or(0),
            price: update.price.unwrap_or(0),
            price_vnum: update.price_vnum.unwrap_or(0),
            price_type: update.price_type.unwrap_or(0),
            sockets,
            attrs,
        }
    }
}

impl DecodedRenewalShopRow {
    /// Materialize this row over a fresh all-zero item slot.
    #[must_use]
    pub fn materialized_item(&self) -> RenewalShopDecodedItem {
        RenewalShopDecodedItem::from_update(&self.item)
    }
}

/// Conversion policy used by [`decode_renewal_shop_query_row_with_policy`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RenewalShopConversionPolicy {
    /// Reject SQL NULLs, prefixes, whitespace, suffixes, and all overflow.
    Strict,
    /// Model the active x86 `str_to_number` overloads and destination casts.
    Legacy,
}

/// Alias making the policy's purpose explicit at call sites.
pub type RenewalShopNumericPolicy = RenewalShopConversionPolicy;
/// Alias for [`RenewalShopConversionPolicy::Legacy`].
pub const RENEWAL_SHOP_LEGACY_CONVERSION_POLICY: RenewalShopConversionPolicy =
    RenewalShopConversionPolicy::Legacy;
/// Alias for [`RenewalShopConversionPolicy::Strict`].
pub const RENEWAL_SHOP_STRICT_CONVERSION_POLICY: RenewalShopConversionPolicy =
    RenewalShopConversionPolicy::Strict;

/// Decode one row using strict, complete decimal conversion.
///
/// # Errors
///
/// Returns a typed [`RenewalShopRowError`] for a wrong row width, SQL NULL,
/// invalid numeric text, numeric overflow, or malformed raw name.
pub fn decode_renewal_shop_query_row(
    row: &RenewalShopQueryRow,
) -> Result<DecodedRenewalShopRow, RenewalShopRowError> {
    decode_renewal_shop_query_row_strict(row)
}

/// Strict-policy spelling of [`decode_renewal_shop_query_row`].
///
/// # Errors
///
/// Returns a typed [`RenewalShopRowError`] for a wrong row width, SQL NULL,
/// invalid numeric text, numeric overflow, or malformed raw name.
pub fn decode_renewal_shop_query_row_strict(
    row: &RenewalShopQueryRow,
) -> Result<DecodedRenewalShopRow, RenewalShopRowError> {
    check_row_width(row)?;
    let columns = row.columns();
    let shop_vnum = strict_i32(&columns[0], 0)?;
    let shop_name = copy_raw_name(&columns[1], 1)?;
    let npc_vnum = Some(strict_u32(&columns[2], 2)?);
    let item = strict_row_item(row)?;
    Ok(DecodedRenewalShopRow {
        shop_vnum,
        shop_name,
        npc_vnum,
        item,
    })
}

/// Decode one row using the explicitly named legacy x86 conversion policy.
///
/// # Errors
///
/// Returns a typed [`RenewalShopRowError`] for a wrong row width, source cell
/// error, or malformed raw name. Numeric NULLs and unparsable-but-nonempty
/// legacy cells are represented by the stateful `Option` fields.
///
/// Numeric `NULL`, empty, and first-NUL cells produce `None` updates.  A
/// non-empty cell, including whitespace or an invalid prefix, produces a
/// value according to the C parser.  The latter is why this API does not
/// return a fully materialized item: `None` is stateful destination data.
pub fn decode_renewal_shop_query_row_legacy(
    row: &RenewalShopQueryRow,
) -> Result<DecodedRenewalShopRow, RenewalShopRowError> {
    check_row_width(row)?;
    let columns = row.columns();
    // The C++ local `iShopVnum` is initialized to zero and
    // `str_to_number` leaves it unchanged for NULL/empty/first-NUL input.
    // Consequently those rows are grouped under signed key zero.
    let shop_vnum = legacy_optional_i32(&columns[0], 0)?.unwrap_or(0);
    let shop_name = copy_raw_name(&columns[1], 1)?;
    let npc_vnum = legacy_optional_u32(&columns[2], 2)?;
    let item = legacy_row_item(row)?;
    Ok(DecodedRenewalShopRow {
        shop_vnum,
        shop_name,
        npc_vnum,
        item,
    })
}

/// Decode one row with an explicit policy.
///
/// # Errors
///
/// Returns the same typed [`RenewalShopRowError`] as the selected policy.
pub fn decode_renewal_shop_query_row_with_policy(
    row: &RenewalShopQueryRow,
    policy: RenewalShopConversionPolicy,
) -> Result<DecodedRenewalShopRow, RenewalShopRowError> {
    match policy {
        RenewalShopConversionPolicy::Strict => decode_renewal_shop_query_row_strict(row),
        RenewalShopConversionPolicy::Legacy => decode_renewal_shop_query_row_legacy(row),
    }
}

/// Compatibility spelling used by SQL-free adapters.
///
/// # Errors
///
/// Returns a typed [`RenewalShopRowError`] under the strict policy.
pub fn decode_renewal_shop_row(
    row: &RenewalShopQueryRow,
) -> Result<DecodedRenewalShopRow, RenewalShopRowError> {
    decode_renewal_shop_query_row_strict(row)
}

/// Compatibility spelling for the legacy row decoder.
///
/// # Errors
///
/// Returns a typed [`RenewalShopRowError`] under the legacy policy.
pub fn decode_renewal_shop_row_legacy(
    row: &RenewalShopQueryRow,
) -> Result<DecodedRenewalShopRow, RenewalShopRowError> {
    decode_renewal_shop_query_row_legacy(row)
}

/// Compatibility aliases for row decoder names.
/// Alias for the typed renewal-shop row decoder error.
pub type DecodeRenewalShopQueryRowError = RenewalShopRowError;
/// Alias for a decoded renewal-shop row.
pub type DecodedRenewalShopQueryRow = DecodedRenewalShopRow;
/// Alias for a decoded row using the legacy policy.
pub type LegacyDecodedRenewalShopRow = DecodedRenewalShopRow;

/// Caller-selected output limits for a renewal-shop section.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RenewalShopSectionLimits {
    /// Maximum number of distinct signed shop groups.
    pub max_records: usize,
    /// Maximum packed section-data bytes.
    pub max_data_bytes: usize,
}

impl RenewalShopSectionLimits {
    /// Construct limits with no additional byte cap.
    #[must_use]
    pub const fn new(max_records: usize) -> Self {
        Self {
            max_records,
            max_data_bytes: usize::MAX,
        }
    }

    /// Construct both group and packed-byte limits.
    #[must_use]
    pub const fn with_data_limit(max_records: usize, max_data_bytes: usize) -> Self {
        Self {
            max_records,
            max_data_bytes,
        }
    }

    /// Alias emphasizing that records are distinct shops.
    #[must_use]
    pub const fn max_shops(&self) -> usize {
        self.max_records
    }
}

impl Default for RenewalShopSectionLimits {
    fn default() -> Self {
        Self {
            max_records: RENEWAL_SHOP_TABLE_MAX_RECORDS,
            max_data_bytes: RENEWAL_SHOP_TABLE_MAX_SECTION_BYTES,
        }
    }
}

/// Reusable SQL-free projection builder.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RenewalShopSectionBuilder {
    limits: RenewalShopSectionLimits,
}

impl RenewalShopSectionBuilder {
    /// Construct a builder with default limits.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            limits: RenewalShopSectionLimits {
                max_records: RENEWAL_SHOP_TABLE_MAX_RECORDS,
                max_data_bytes: RENEWAL_SHOP_TABLE_MAX_SECTION_BYTES,
            },
        }
    }

    /// Construct a builder with a caller-selected group limit.
    #[must_use]
    pub const fn with_limit(max_records: usize) -> Self {
        Self {
            limits: RenewalShopSectionLimits::new(max_records),
        }
    }

    /// Construct a builder with explicit limits.
    #[must_use]
    pub const fn with_limits(limits: RenewalShopSectionLimits) -> Self {
        Self { limits }
    }

    /// Borrow configured limits.
    #[must_use]
    pub const fn limits(&self) -> RenewalShopSectionLimits {
        self.limits
    }

    /// Build a strict section.
    ///
    /// # Errors
    ///
    /// See [`build_renewal_shop_section_with_limits`].
    pub fn build(
        &self,
        rows: &[RenewalShopQueryRow],
    ) -> Result<BootSection, RenewalShopSectionError> {
        build_renewal_shop_section_with_limits(rows, self.limits)
    }

    /// Build a legacy-policy section.
    ///
    /// # Errors
    ///
    /// See [`build_renewal_shop_section_legacy_with_limits`].
    pub fn build_legacy(
        &self,
        rows: &[RenewalShopQueryRow],
    ) -> Result<BootSection, RenewalShopSectionError> {
        build_renewal_shop_section_legacy_with_limits(rows, self.limits)
    }

    /// Build with an explicit conversion policy.
    ///
    /// # Errors
    ///
    /// See [`build_renewal_shop_section_with_policy`].
    pub fn build_with_policy(
        &self,
        rows: &[RenewalShopQueryRow],
        policy: RenewalShopConversionPolicy,
    ) -> Result<BootSection, RenewalShopSectionError> {
        match policy {
            RenewalShopConversionPolicy::Strict => self.build(rows),
            RenewalShopConversionPolicy::Legacy => self.build_legacy(rows),
        }
    }
}

impl Default for RenewalShopSectionBuilder {
    fn default() -> Self {
        Self::new()
    }
}

/// Compatibility name for [`RenewalShopSectionBuilder`].
pub type RenewalShopTableBuilder = RenewalShopSectionBuilder;

/// A checked renewal-shop section error.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RenewalShopSectionError {
    /// More distinct shops were supplied than the caller permits.
    TooManyShops {
        /// Number of distinct shop groups.
        count: usize,
        /// Configured maximum.
        maximum: usize,
    },
    /// The injected source exceeded a defensive acquisition bound.
    TooManySourceRows {
        /// Number of source rows supplied.
        count: usize,
        /// Configured maximum.
        maximum: usize,
    },
    /// Distinct shop count cannot be represented by the boot `u16` count.
    CountOverflow {
        /// Number of distinct shop groups.
        count: usize,
    },
    /// Fixed record width cannot be represented by the boot `u16` width.
    RecordSizeOverflow {
        /// Fixed record width.
        size: usize,
    },
    /// Packed data-size arithmetic overflowed `usize`.
    DataSizeOverflow {
        /// Shop count used in the multiplication.
        count: usize,
    },
    /// Output or group storage could not reserve a checked bound.
    AllocationFailed {
        /// Requested allocation size or item count.
        requested: usize,
    },
    /// Packed data exceeds the caller's byte limit.
    DataTooLarge {
        /// Required packed data length.
        length: usize,
        /// Configured byte limit.
        maximum: usize,
    },
    /// A shop attempted to address more than its fixed 40-item capacity.
    ItemCapacityOverflow {
        /// Signed source map key.
        shop_vnum: i32,
        /// Number of items after the attempted write.
        count: usize,
        /// Fixed source capacity.
        maximum: usize,
    },
    /// Protocol encoding returned an unexpected record width.
    RecordSizeMismatch {
        /// Zero-based output shop index.
        index: usize,
        /// Required packed width.
        expected: usize,
        /// Actual encoded width.
        actual: usize,
    },
    /// A source row could not be decoded.
    Row {
        /// Zero-based source row index.
        index: usize,
        /// Row error.
        source: RenewalShopRowError,
    },
}

impl fmt::Display for RenewalShopSectionError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::TooManyShops { count, maximum } => write!(
                formatter,
                "renewal-shop query produced {count} distinct shops; maximum is {maximum}"
            ),
            Self::TooManySourceRows { count, maximum } => write!(
                formatter,
                "renewal-shop query produced {count} source rows; maximum is {maximum}"
            ),
            Self::CountOverflow { count } => {
                write!(formatter, "renewal-shop count {count} does not fit u16")
            }
            Self::RecordSizeOverflow { size } => write!(
                formatter,
                "renewal-shop record size {size} does not fit u16"
            ),
            Self::DataSizeOverflow { count } => write!(
                formatter,
                "renewal-shop data size overflows usize for {count} records"
            ),
            Self::AllocationFailed { requested } => write!(
                formatter,
                "renewal-shop allocation of {requested} units failed"
            ),
            Self::DataTooLarge { length, maximum } => write!(
                formatter,
                "renewal-shop data length {length} exceeds maximum {maximum}"
            ),
            Self::ItemCapacityOverflow {
                shop_vnum,
                count,
                maximum,
            } => write!(
                formatter,
                "renewal-shop {shop_vnum} attempted item {count}; fixed maximum is {maximum}"
            ),
            Self::RecordSizeMismatch {
                index,
                expected,
                actual,
            } => write!(
                formatter,
                "renewal-shop record {index} encoded to {actual} bytes; expected {expected}"
            ),
            Self::Row { index, source } => {
                write!(formatter, "renewal-shop row {index}: {source}")
            }
        }
    }
}

impl Error for RenewalShopSectionError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Row { source, .. } => Some(source),
            _ => None,
        }
    }
}

struct RenewalShopGroup {
    npc_vnum: u32,
    shop_name: [u8; RENEWAL_SHOP_NAME_BYTES],
    items: Vec<ShopItemRecord>,
    item_count: usize,
}

impl RenewalShopGroup {
    fn new() -> Self {
        Self {
            npc_vnum: 0,
            shop_name: [0; RENEWAL_SHOP_NAME_BYTES],
            // The pending slot is already part of the source's zeroed
            // destination.  Keeping it in the vector makes repeated writes
            // stateful without materializing 40 slots per group.
            items: vec![ShopItemRecord::zeroed_renewal_slot()],
            item_count: 0,
        }
    }

    fn apply(
        &mut self,
        shop_vnum: i32,
        decoded: &DecodedRenewalShopRow,
    ) -> Result<(), RenewalShopSectionError> {
        if self.item_count >= RENEWAL_SHOP_ITEM_MAX_NUM {
            return Err(RenewalShopSectionError::ItemCapacityOverflow {
                shop_vnum,
                count: self.item_count + 1,
                maximum: RENEWAL_SHOP_ITEM_MAX_NUM,
            });
        }
        let index = self.item_count;
        if self.items.len() <= index {
            let additional = index + 1 - self.items.len();
            self.items.try_reserve(additional).map_err(|_| {
                RenewalShopSectionError::AllocationFailed {
                    requested: additional,
                }
            })?;
            self.items
                .extend((self.items.len()..=index).map(|_| ShopItemRecord::zeroed_renewal_slot()));
        }

        self.shop_name = decoded.shop_name;
        if let Some(npc_vnum) = decoded.npc_vnum {
            self.npc_vnum = npc_vnum;
        }

        let item = &mut self.items[index];
        if let Some(vnum) = decoded.item.vnum {
            item.vnum = vnum;
        }
        if let Some(count) = decoded.item.count {
            item.count = count;
        }
        if let Some(price) = decoded.item.price {
            item.price = price;
        }
        if let Some(price_vnum) = decoded.item.price_vnum {
            item.price_vnum = price_vnum;
        }
        if let Some(price_type) = decoded.item.price_type {
            item.price_type = price_type;
        }
        for (slot, value) in item.sockets.iter_mut().zip(decoded.item.sockets) {
            if let Some(value) = value {
                *slot = value;
            }
        }
        for (slot, value) in item.attrs.iter_mut().zip(decoded.item.attrs) {
            if let Some(attr_type) = value.attr_type {
                slot.attr_type = attr_type;
            }
            if let Some(value) = value.value {
                slot.value = value;
            }
        }

        // This is intentionally the resulting slot vnum, not the raw cell.
        // It preserves the source behavior for a zero/NULL vnum row.
        if item.vnum != 0 {
            self.item_count += 1;
        }
        Ok(())
    }
}

fn validate_section_size(
    count: usize,
    limits: RenewalShopSectionLimits,
) -> Result<(u16, u16, usize), RenewalShopSectionError> {
    if count > limits.max_records {
        return Err(RenewalShopSectionError::TooManyShops {
            count,
            maximum: limits.max_records,
        });
    }
    let wire_count =
        u16::try_from(count).map_err(|_| RenewalShopSectionError::CountOverflow { count })?;
    let record_size = u16::try_from(RENEWAL_SHOP_TABLE_WIRE_SIZE).map_err(|_| {
        RenewalShopSectionError::RecordSizeOverflow {
            size: RENEWAL_SHOP_TABLE_WIRE_SIZE,
        }
    })?;
    let data_len = RENEWAL_SHOP_TABLE_WIRE_SIZE
        .checked_mul(count)
        .ok_or(RenewalShopSectionError::DataSizeOverflow { count })?;
    if data_len > limits.max_data_bytes {
        return Err(RenewalShopSectionError::DataTooLarge {
            length: data_len,
            maximum: limits.max_data_bytes,
        });
    }
    Ok((wire_count, record_size, data_len))
}

/// Validate count, record-width, and packed-data arithmetic without decoding
/// rows or allocating output.
///
/// # Errors
///
/// Returns [`RenewalShopSectionError`] for configured limits, `u16` overflow,
/// or checked `usize` overflow.
pub fn checked_renewal_shop_section_size(
    count: usize,
    limits: RenewalShopSectionLimits,
) -> Result<(u16, u16, usize), RenewalShopSectionError> {
    validate_section_size(count, limits)
}

fn append_projection(
    rows: &[RenewalShopQueryRow],
    limits: RenewalShopSectionLimits,
    legacy: bool,
) -> Result<BootSection, RenewalShopSectionError> {
    // A repeated zero-vnum row can be legal source input.  We do not derive a
    // `max_records * 40` bound before processing, so capacity errors retain
    // their source-order meaning.  The global ceiling is only a last-resort
    // guard against an injected slice that cannot plausibly be a query result.
    if rows.len() > RENEWAL_SHOP_TABLE_MAX_SOURCE_ROWS {
        return Err(RenewalShopSectionError::TooManySourceRows {
            count: rows.len(),
            maximum: RENEWAL_SHOP_TABLE_MAX_SOURCE_ROWS,
        });
    }

    let mut groups: BTreeMap<i32, RenewalShopGroup> = BTreeMap::new();
    for (index, row) in rows.iter().enumerate() {
        let decoded = if legacy {
            decode_renewal_shop_query_row_legacy(row)
        } else {
            decode_renewal_shop_query_row_strict(row)
        }
        .map_err(|source| RenewalShopSectionError::Row { index, source })?;

        if !groups.contains_key(&decoded.shop_vnum) && groups.len() >= limits.max_records {
            return Err(RenewalShopSectionError::TooManyShops {
                count: groups.len() + 1,
                maximum: limits.max_records,
            });
        }
        let group = groups
            .entry(decoded.shop_vnum)
            .or_insert_with(RenewalShopGroup::new);
        group.apply(decoded.shop_vnum, &decoded)?;
    }

    // Treat the usual `max_records * 40` bound as an acquisition policy only
    // after source-order item-capacity handling.  It protects a custom
    // adapter from unbounded duplicate input while leaving zero-vnum semantics
    // observable in the normal case.
    if limits.max_records > 0 {
        let maximum = renewal_shop_source_row_limit(limits.max_records)
            .unwrap_or(RENEWAL_SHOP_TABLE_MAX_SOURCE_ROWS);
        if rows.len() > maximum {
            return Err(RenewalShopSectionError::TooManySourceRows {
                count: rows.len(),
                maximum,
            });
        }
    }

    let (count, record_size, data_len) = validate_section_size(groups.len(), limits)?;
    let mut data = Vec::new();
    data.try_reserve_exact(data_len)
        .map_err(|_| RenewalShopSectionError::AllocationFailed {
            requested: data_len,
        })?;

    for (index, (shop_vnum, group)) in groups.into_iter().enumerate() {
        let mut record = ShopTableRecord::zeroed_renewal_shop();
        record.vnum = u32::from_le_bytes(shop_vnum.to_le_bytes());
        record.npc_vnum = group.npc_vnum;
        record.shop_name = group.shop_name;
        record.item_count = u8::try_from(group.item_count).map_err(|_| {
            RenewalShopSectionError::ItemCapacityOverflow {
                shop_vnum,
                count: group.item_count,
                maximum: RENEWAL_SHOP_ITEM_MAX_NUM,
            }
        })?;
        for (slot, item) in record.items.iter_mut().zip(group.items) {
            *slot = item;
        }
        let encoded = RecordCodec::encode(&record);
        if encoded.len() != RENEWAL_SHOP_TABLE_WIRE_SIZE {
            return Err(RenewalShopSectionError::RecordSizeMismatch {
                index,
                expected: RENEWAL_SHOP_TABLE_WIRE_SIZE,
                actual: encoded.len(),
            });
        }
        data.extend_from_slice(&encoded);
    }

    debug_assert_eq!(data.len(), data_len);
    Ok(BootSection {
        kind: BootSectionKind::RenewalShop,
        record_size,
        count,
        data,
    })
}

/// Build a strict renewal-shop section with default limits.
///
/// An empty input is valid and returns an empty `RenewalShop` section.
///
/// # Errors
///
/// Returns [`RenewalShopSectionError`] for a malformed row, fixed-capacity
/// violation, count/width/size overflow, allocation failure, or limit failure.
pub fn build_renewal_shop_section(
    rows: &[RenewalShopQueryRow],
) -> Result<BootSection, RenewalShopSectionError> {
    build_renewal_shop_section_with_limits(rows, RenewalShopSectionLimits::default())
}

/// Build a strict renewal-shop section with a caller-selected group limit.
///
/// # Errors
///
/// Returns [`RenewalShopSectionError`] for invalid rows, capacity violations,
/// count/size overflow, allocation failure, or limit failure.
pub fn build_renewal_shop_section_with_limit(
    rows: &[RenewalShopQueryRow],
    max_records: usize,
) -> Result<BootSection, RenewalShopSectionError> {
    build_renewal_shop_section_with_limits(rows, RenewalShopSectionLimits::new(max_records))
}

/// Build a strict renewal-shop section with explicit limits.
///
/// # Errors
///
/// Returns [`RenewalShopSectionError`] for invalid rows, capacity violations,
/// count/width/size overflow, allocation failure, or limit failure.
pub fn build_renewal_shop_section_with_limits(
    rows: &[RenewalShopQueryRow],
    limits: RenewalShopSectionLimits,
) -> Result<BootSection, RenewalShopSectionError> {
    append_projection(rows, limits, false)
}

/// Build a renewal-shop section using the explicitly named legacy policy.
///
/// # Errors
///
/// Returns [`RenewalShopSectionError`] for source errors, name errors,
/// capacity violations, count/size overflow, allocation failure, or limit
/// failure.
pub fn build_renewal_shop_section_legacy(
    rows: &[RenewalShopQueryRow],
) -> Result<BootSection, RenewalShopSectionError> {
    build_renewal_shop_section_legacy_with_limits(rows, RenewalShopSectionLimits::default())
}

/// Build a legacy-policy renewal-shop section with a group limit.
///
/// # Errors
///
/// Returns [`RenewalShopSectionError`] for source/name errors, capacity
/// violations, count/size overflow, allocation failure, or limit failure.
pub fn build_renewal_shop_section_legacy_with_limit(
    rows: &[RenewalShopQueryRow],
    max_records: usize,
) -> Result<BootSection, RenewalShopSectionError> {
    build_renewal_shop_section_legacy_with_limits(rows, RenewalShopSectionLimits::new(max_records))
}

/// Build a legacy-policy renewal-shop section with explicit limits.
///
/// # Errors
///
/// Returns [`RenewalShopSectionError`] for source/name errors, capacity
/// violations, count/size overflow, allocation failure, or limit failure.
pub fn build_renewal_shop_section_legacy_with_limits(
    rows: &[RenewalShopQueryRow],
    limits: RenewalShopSectionLimits,
) -> Result<BootSection, RenewalShopSectionError> {
    append_projection(rows, limits, true)
}

/// Build a section with an explicit conversion policy.
///
/// # Errors
///
/// Returns [`RenewalShopSectionError`] for policy-specific row errors,
/// capacity violations, count/size overflow, allocation failure, or limit
/// failure.
pub fn build_renewal_shop_section_with_policy(
    rows: &[RenewalShopQueryRow],
    policy: RenewalShopConversionPolicy,
) -> Result<BootSection, RenewalShopSectionError> {
    match policy {
        RenewalShopConversionPolicy::Strict => {
            build_renewal_shop_section_with_limits(rows, RenewalShopSectionLimits::default())
        }
        RenewalShopConversionPolicy::Legacy => {
            build_renewal_shop_section_legacy_with_limits(rows, RenewalShopSectionLimits::default())
        }
    }
}

/// A value object carrying the exact legacy renewal-shop statement.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct RenewalShopTableQuery;

impl RenewalShopTableQuery {
    /// Construct the source statement.
    #[must_use]
    pub const fn new() -> Self {
        Self
    }

    /// Return the exact SQL text.
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        RENEWAL_SHOP_TABLE_QUERY
    }

    /// Alias used by SQL adapter traits.
    #[must_use]
    pub const fn statement(&self) -> &'static str {
        RENEWAL_SHOP_TABLE_QUERY
    }

    /// Return the fixed column count.
    #[must_use]
    pub const fn column_count(&self) -> usize {
        RENEWAL_SHOP_TABLE_QUERY_COLUMNS
    }

    /// Return a source column name.
    #[must_use]
    pub const fn column_name(&self, index: usize) -> &'static str {
        renewal_shop_query_column_name(index)
    }
}

/// Short alias for the query value object.
pub type RenewalShopQuery = RenewalShopTableQuery;

/// A source adapter for the fixed renewal-shop query.
///
/// Implementations are SQL-free from this module's point of view.  They may
/// receive rows from any caller-owned acquisition boundary, but this module
/// never opens a connection, selects a profile, or mutates a cache.
pub trait RenewalShopTableRowSource {
    /// Source-specific acquisition error.
    type Error;

    /// Fetch all joined rows in source order.
    ///
    /// # Errors
    ///
    /// Returns the source adapter's acquisition error when row retrieval fails.
    fn query_rows(
        &self,
        query: &RenewalShopTableQuery,
    ) -> Result<Vec<RenewalShopQueryRow>, Self::Error>;
}

impl<F, E> RenewalShopTableRowSource for F
where
    F: Fn(&RenewalShopTableQuery) -> Result<Vec<RenewalShopQueryRow>, E>,
{
    type Error = E;

    fn query_rows(
        &self,
        query: &RenewalShopTableQuery,
    ) -> Result<Vec<RenewalShopQueryRow>, Self::Error> {
        self(query)
    }
}

/// Compatibility name for the row-source trait.
pub use RenewalShopTableRowSource as RenewalShopRowSource;

/// A loader configured with the source statement and output limits.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RenewalShopTableLoader {
    limits: RenewalShopSectionLimits,
}

impl RenewalShopTableLoader {
    /// Construct a loader with default limits.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            limits: RenewalShopSectionLimits {
                max_records: RENEWAL_SHOP_TABLE_MAX_RECORDS,
                max_data_bytes: RENEWAL_SHOP_TABLE_MAX_SECTION_BYTES,
            },
        }
    }

    /// Construct a loader with a caller-selected group limit.
    #[must_use]
    pub const fn with_limit(max_records: usize) -> Self {
        Self {
            limits: RenewalShopSectionLimits::new(max_records),
        }
    }

    /// Construct a loader with explicit limits.
    #[must_use]
    pub const fn with_limits(limits: RenewalShopSectionLimits) -> Self {
        Self { limits }
    }

    /// Alias for [`Self::with_limits`].
    #[must_use]
    pub const fn from_limits(limits: RenewalShopSectionLimits) -> Self {
        Self::with_limits(limits)
    }

    /// Construct a loader with the default section limits.
    #[must_use]
    pub fn default_with_limits() -> Self {
        Self::new()
    }

    /// Borrow the exact statement used by this loader.
    #[must_use]
    pub const fn query(&self) -> RenewalShopTableQuery {
        RenewalShopTableQuery::new()
    }

    /// Borrow configured limits.
    #[must_use]
    pub const fn limits(&self) -> RenewalShopSectionLimits {
        self.limits
    }

    /// Return the exact source statement text.
    #[must_use]
    pub const fn statement(&self) -> &'static str {
        RENEWAL_SHOP_TABLE_QUERY
    }

    /// Alias for [`Self::statement`].
    #[must_use]
    pub const fn as_str(&self) -> &'static str {
        RENEWAL_SHOP_TABLE_QUERY
    }

    /// Return the defensive raw joined-source-row cap for this loader.
    ///
    /// The result is `None` when the distinct-shop limit cannot fit the boot
    /// `u16` count. This is an acquisition bound, not a schema guarantee that
    /// every source row belongs to a distinct shop.
    #[must_use]
    pub const fn source_row_limit(&self) -> Option<usize> {
        renewal_shop_source_row_limit(self.limits.max_records)
    }

    /// Project caller-supplied rows directly with the strict policy.
    ///
    /// # Errors
    ///
    /// Returns [`RenewalShopSectionError`] for malformed rows, fixed-capacity
    /// violations, count or data-size overflow, allocation failure, or limit
    /// failure.
    pub fn load(
        &self,
        rows: &[RenewalShopQueryRow],
    ) -> Result<BootSection, RenewalShopSectionError> {
        build_renewal_shop_section_with_limits(rows, self.limits)
    }

    /// Alias for [`Self::load`].
    ///
    /// # Errors
    ///
    /// Returns the same errors as [`Self::load`].
    pub fn build(
        &self,
        rows: &[RenewalShopQueryRow],
    ) -> Result<BootSection, RenewalShopSectionError> {
        self.load(rows)
    }

    /// Project caller-supplied rows with the named legacy policy.
    ///
    /// # Errors
    ///
    /// Returns the same row, capacity, and limit errors as [`Self::load`].
    pub fn load_legacy(
        &self,
        rows: &[RenewalShopQueryRow],
    ) -> Result<BootSection, RenewalShopSectionError> {
        build_renewal_shop_section_legacy_with_limits(rows, self.limits)
    }

    /// Load an injected source with the strict policy.
    ///
    /// # Errors
    ///
    /// Returns [`RenewalShopTableLoadError`] for source or section failure.
    pub fn load_source<S>(
        &self,
        source: &S,
    ) -> Result<BootSection, RenewalShopTableLoadError<S::Error>>
    where
        S: RenewalShopTableRowSource,
    {
        self.load_section(source)
    }

    /// Load and strictly project rows from an injected source.
    ///
    /// # Errors
    ///
    /// Returns [`RenewalShopTableLoadError::Source`] for source failures and
    /// [`RenewalShopTableLoadError::Rows`] for projection failures.
    pub fn load_section<S>(
        &self,
        source: &S,
    ) -> Result<BootSection, RenewalShopTableLoadError<S::Error>>
    where
        S: RenewalShopTableRowSource,
    {
        let rows = source
            .query_rows(&self.query())
            .map_err(RenewalShopTableLoadError::Source)?;
        build_renewal_shop_section_with_limits(&rows, self.limits)
            .map_err(RenewalShopTableLoadError::Rows)
    }

    /// Load and project rows using the explicitly named legacy policy.
    ///
    /// # Errors
    ///
    /// Returns [`RenewalShopTableLoadError::Source`] for source failures and
    /// [`RenewalShopTableLoadError::Rows`] for projection failures.
    pub fn load_section_legacy<S>(
        &self,
        source: &S,
    ) -> Result<BootSection, RenewalShopTableLoadError<S::Error>>
    where
        S: RenewalShopTableRowSource,
    {
        let rows = source
            .query_rows(&self.query())
            .map_err(RenewalShopTableLoadError::Source)?;
        build_renewal_shop_section_legacy_with_limits(&rows, self.limits)
            .map_err(RenewalShopTableLoadError::Rows)
    }
}

impl Default for RenewalShopTableLoader {
    fn default() -> Self {
        Self::new()
    }
}

/// A source or projection error from the injected loader boundary.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RenewalShopTableLoadError<E> {
    /// The caller-owned row source failed.
    Source(E),
    /// The source returned rows that could not be projected.
    Rows(RenewalShopSectionError),
}

impl<E> fmt::Display for RenewalShopTableLoadError<E>
where
    E: fmt::Display,
{
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Source(error) => write!(formatter, "renewal-shop source failed: {error}"),
            Self::Rows(error) => write!(formatter, "renewal-shop projection failed: {error}"),
        }
    }
}

impl<E> Error for RenewalShopTableLoadError<E>
where
    E: Error + 'static,
{
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Source(error) => Some(error),
            Self::Rows(error) => Some(error),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use protocol::db_records::ShopItemPosition;

    fn text(value: impl Into<String>) -> RenewalShopQueryValue {
        RenewalShopQueryValue::Text(value.into())
    }

    fn bytes(value: &[u8]) -> RenewalShopQueryValue {
        RenewalShopQueryValue::Bytes(value.to_vec())
    }

    #[allow(clippy::too_many_arguments)]
    fn row_with(
        shop: i32,
        name: &[u8],
        npc: &str,
        vnum: &str,
        count: &str,
        price: &str,
        price_vnum: &str,
        price_type: &str,
    ) -> RenewalShopQueryRow {
        RenewalShopQueryRow::new(vec![
            text(shop.to_string()),
            bytes(name),
            text(npc),
            text(vnum),
            text(count),
            text(price),
            text(price_vnum),
            text(price_type),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
            text("0"),
        ])
    }

    fn row(shop: i32, vnum: u32) -> RenewalShopQueryRow {
        row_with(shop, b"shop", "7", &vnum.to_string(), "1", "99", "0", "1")
    }

    fn record_at(section: &BootSection, index: usize) -> ShopTableRecord {
        let start = index * RENEWAL_SHOP_TABLE_WIRE_SIZE;
        let end = start + RENEWAL_SHOP_TABLE_WIRE_SIZE;
        ShopTableRecord::decode(&section.data[start..end]).expect("valid packed record")
    }

    #[test]
    fn query_has_source_spelling_and_width() {
        assert_eq!(RENEWAL_SHOP_TABLE_QUERY.len(), 497);
        assert_eq!(RENEWAL_SHOP_TABLE_QUERY_COLUMNS, 28);
        assert!(RENEWAL_SHOP_TABLE_QUERY.contains("attrvalue0 , attrtype1"));
        assert!(RENEWAL_SHOP_TABLE_QUERY.ends_with("ORDER BY shopex.vnum, shopex_item.item_vnum"));
        assert_eq!(renewal_shop_column_name_for_test(0), "shopex.vnum");
        assert_eq!(renewal_shop_column_name_for_test(27), "attrvalue6");
        assert_eq!(renewal_shop_column_name_for_test(28), "unknown");
    }

    fn renewal_shop_column_name_for_test(index: usize) -> &'static str {
        renewal_shop_query_column_name(index)
    }

    #[test]
    fn empty_result_is_a_valid_renewal_section() {
        let section = build_renewal_shop_section(&[]).expect("empty source is valid");
        assert_eq!(section.kind, BootSectionKind::RenewalShop);
        assert_eq!(section.record_size, 2_762);
        assert_eq!(section.count, 0);
        assert!(section.data.is_empty());
    }

    #[test]
    fn groups_emit_signed_order_and_preserve_duplicate_item_order() {
        let mut first = row(2, 20);
        first.columns[1] = bytes(b"two-a");
        let mut first_duplicate = row(2, 21);
        first_duplicate.columns[1] = bytes(b"two-b");
        let negative = row(-1, 9);
        let section =
            build_renewal_shop_section(&[first, negative, first_duplicate]).expect("strict rows");
        assert_eq!(section.count, 2);
        let negative_record = record_at(&section, 0);
        assert_eq!(negative_record.vnum, u32::MAX);
        assert_eq!(negative_record.item_count, 1);
        let two_record = record_at(&section, 1);
        assert_eq!(two_record.vnum, 2);
        assert_eq!(two_record.shop_name[..6], *b"two-b\0");
        assert_eq!(two_record.items[0].vnum, 20);
        assert_eq!(two_record.items[1].vnum, 21);
    }

    #[test]
    fn renewal_constructor_is_true_zero_not_base_shop_defaults() {
        let mut no_item = row_with(1, b"no-item", "12", "0", "0", "0", "0", "0");
        for cell in &mut no_item.columns[3..] {
            *cell = RenewalShopQueryValue::Null;
        }
        let section = build_renewal_shop_section_legacy(&[no_item]).expect("legacy NULL item");
        let record = record_at(&section, 0);
        assert_eq!(record.item_count, 0);
        assert_eq!(record.items[0].pos, ShopItemPosition::new(0, 0));
        assert_eq!(record.items[0].price_type, 0);
        assert_eq!(record.items[1], ShopItemRecord::zeroed_renewal_slot());
    }

    #[test]
    fn zero_vnum_pending_slot_is_written_but_does_not_advance_count() {
        let mut pending = row_with(9, b"pending", "3", "0", "4", "555", "0", "2");
        pending.columns[8] = text("-7");
        pending.columns[14] = text("3");
        pending.columns[15] = text("-9");
        let section = build_renewal_shop_section_legacy(&[pending]).expect("pending row");
        let record = record_at(&section, 0);
        assert_eq!(record.item_count, 0);
        assert_eq!(record.items[0].vnum, 0);
        assert_eq!(record.items[0].count, 4);
        assert_eq!(record.items[0].price, 555);
        assert_eq!(record.items[0].sockets[0], -7);
        assert_eq!(record.items[0].attrs[0].attr_type, 3);
        assert_eq!(record.items[0].attrs[0].value, -9);
        assert_eq!(record.items[1].price, 0);
    }

    #[test]
    fn reused_slot_preserves_each_destination_field() {
        let mut first = row_with(4, b"a", "10", "0", "11", "100", "12", "13");
        first.columns[8] = text("21");
        first.columns[14] = text("31");
        first.columns[15] = text("41");
        let mut overwrite = row_with(4, b"b", "11", "0", "0", "0", "0", "0");
        overwrite.columns[3] = RenewalShopQueryValue::Null;
        overwrite.columns[4] = text("bad");
        overwrite.columns[5] = RenewalShopQueryValue::Null;
        overwrite.columns[8] = RenewalShopQueryValue::Null;
        overwrite.columns[14] = text("bad");
        overwrite.columns[15] = RenewalShopQueryValue::Null;
        let mut commit = row_with(4, b"c", "12", "77", "0", "900", "0", "0");
        commit.columns[4] = RenewalShopQueryValue::Null;
        commit.columns[8] = RenewalShopQueryValue::Null;
        commit.columns[14] = RenewalShopQueryValue::Null;
        commit.columns[15] = RenewalShopQueryValue::Null;
        let section =
            build_renewal_shop_section_legacy(&[first, overwrite, commit]).expect("reused slot");
        let record = record_at(&section, 0);
        assert_eq!(record.item_count, 1);
        assert_eq!(record.items[0].vnum, 77);
        assert_eq!(record.items[0].count, 0); // "bad" wrote zero.
        assert_eq!(record.items[0].price, 900); // The final row supplied 900.
        assert_eq!(record.items[0].price_vnum, 0); // The final row supplied zero.
        assert_eq!(record.items[0].price_type, 0); // The final row supplied zero.
        assert_eq!(record.items[0].sockets[0], 21); // NULL retained.
        assert_eq!(record.items[0].attrs[0].attr_type, 0); // "bad" wrote zero.
        assert_eq!(record.items[0].attrs[0].value, 41); // NULL retained.
        assert_eq!(&record.shop_name[..2], &[b'c', 0]);
        assert_eq!(record.npc_vnum, 12);
    }

    #[test]
    fn legacy_null_npc_and_leading_nul_preserve_destination() {
        let first = row_with(1, b"first", "55", "0", "0", "0", "0", "0");
        let mut second = row_with(1, b"second", "", "0", "0", "0", "0", "0");
        second.columns[2] = bytes(b"\0 88");
        let section = build_renewal_shop_section_legacy(&[first, second]).expect("legacy NPC");
        assert_eq!(record_at(&section, 0).npc_vnum, 55);
    }

    #[test]
    fn legacy_numeric_prefixes_and_x86_casts_are_explicit() {
        let mut source = row_with(
            1,
            b"n",
            " 42x",
            " 100x",
            " 65536x",
            " 18446744073709551616x",
            " -1x",
            " 256x",
        );
        source.columns[8] = text(" -1tail");
        source.columns[14] = text("32768tail");
        source.columns[15] = text("-32769tail");
        let decoded = decode_renewal_shop_query_row_legacy(&source).expect("legacy parser");
        assert_eq!(decoded.shop_vnum, 1);
        assert_eq!(decoded.npc_vnum, Some(42));
        assert_eq!(decoded.item.vnum, Some(100));
        assert_eq!(decoded.item.count, Some(0)); // strtoul 32 -> ushort low bits.
        assert_eq!(decoded.item.price, Some(u64::MAX));
        assert_eq!(decoded.item.price_vnum, Some(u32::MAX));
        assert_eq!(decoded.item.price_type, Some(0));
        assert_eq!(decoded.item.sockets[0], Some(-1));
        assert_eq!(decoded.item.attrs[0].attr_type, Some(0));
        assert_eq!(decoded.item.attrs[0].value, Some(32767));
    }

    #[test]
    fn strict_policy_rejects_prefixes_suffixes_and_overflow() {
        let mut source = row(1, 1);
        source.columns[3] = text(" 1x");
        assert!(matches!(
            decode_renewal_shop_query_row(&source),
            Err(RenewalShopRowError::InvalidNumber { column: 3, .. })
        ));
        source.columns[3] = text("4294967296");
        assert!(matches!(
            decode_renewal_shop_query_row(&source),
            Err(RenewalShopRowError::NumberOverflow { column: 3, .. })
        ));
        source.columns[3] = RenewalShopQueryValue::Null;
        assert!(matches!(
            decode_renewal_shop_query_row(&source),
            Err(RenewalShopRowError::Null { column: 3 })
        ));
    }

    #[test]
    fn name_copy_is_raw_fixed_width_and_null_is_typed() {
        let raw = [0_u8, b'A', b'B', 0xFF];
        let mut source = row_with(1, &raw, "1", "0", "0", "0", "0", "0");
        source.columns[1] = bytes(&[b'X'; 40]);
        let decoded = decode_renewal_shop_query_row_legacy(&source).expect("raw name");
        assert_eq!(&decoded.shop_name[..4], &[b'X'; 4]);
        assert_eq!(decoded.shop_name[32], b'X');
        let raw_decoded =
            decode_renewal_shop_query_row_legacy(&row_with(1, &raw, "1", "0", "0", "0", "0", "0"))
                .expect("raw embedded-NUL name");
        assert_eq!(&raw_decoded.shop_name[..4], &raw);
        assert!(raw_decoded.shop_name[4..].iter().all(|byte| *byte == 0));
        let mut null_name = source.clone();
        null_name.columns[1] = RenewalShopQueryValue::Null;
        assert!(matches!(
            decode_renewal_shop_query_row_legacy(&null_name),
            Err(RenewalShopRowError::Null { column: 1 })
        ));
        let mut short_name = row_with(1, b"hi", "1", "0", "0", "0", "0", "0");
        short_name.columns[1] = bytes(&[0, b'A', 0, b'B']);
        let short = decode_renewal_shop_query_row_legacy(&short_name).unwrap();
        assert_eq!(&short.shop_name[..4], &[0, b'A', 0, b'B']);
        assert!(short.shop_name[4..].iter().all(|byte| *byte == 0));
    }

    #[test]
    fn capacity_overflow_is_rejected_even_for_a_trailing_zero_vnum() {
        let mut rows = Vec::new();
        for vnum in 1..=40 {
            rows.push(row(8, vnum));
        }
        rows.push(row(8, 0));
        assert!(matches!(
            build_renewal_shop_section_legacy(&rows),
            Err(RenewalShopSectionError::ItemCapacityOverflow {
                shop_vnum: 8,
                count: 41,
                maximum: 40
            })
        ));
    }

    #[test]
    fn limits_and_row_shape_are_checked() {
        let section_error = build_renewal_shop_section_with_limits(
            &[row(1, 1), row(2, 1)],
            RenewalShopSectionLimits::with_data_limit(1, 2_762),
        )
        .expect_err("one-group cap");
        assert!(matches!(
            section_error,
            RenewalShopSectionError::TooManyShops {
                count: 2,
                maximum: 1
            }
        ));
        let data_error = build_renewal_shop_section_with_limit(&[row(1, 1)], 1)
            .expect("default byte limit is not exceeded");
        assert_eq!(data_error.data.len(), 2_762);
        let size_error = checked_renewal_shop_section_size(
            1,
            RenewalShopSectionLimits::with_data_limit(1, 2_761),
        )
        .expect_err("byte cap");
        assert!(matches!(
            size_error,
            RenewalShopSectionError::DataTooLarge { .. }
        ));
        let wrong = RenewalShopQueryRow::new(vec![text("1")]);
        assert!(matches!(
            build_renewal_shop_section(&[wrong]),
            Err(RenewalShopSectionError::Row {
                index: 0,
                source: RenewalShopRowError::ColumnCount { .. }
            })
        ));
    }

    #[test]
    fn packed_record_keeps_true_zero_wire_fields() {
        let section = build_renewal_shop_section_legacy(&[row_with(
            1,
            b"wire",
            "16909060",
            "84281096",
            "2314",
            "72623859790382856",
            "286397204",
            "21",
        )])
        .expect("wire row");
        let encoded = &section.data[..RENEWAL_SHOP_TABLE_WIRE_SIZE];
        assert_eq!(&encoded[0..4], &[1, 0, 0, 0]);
        assert_eq!(&encoded[4..8], &[4, 3, 2, 1]);
        // The table count byte precedes the first item; item vnum/count then
        // begin at offsets 9 and 13 in the packed source layout.
        assert_eq!(encoded[8], 1);
        assert_eq!(&encoded[9..13], &[8, 7, 6, 5]);
        assert_eq!(&encoded[13..15], &[10, 9]);
        assert_eq!(&encoded[15..18], &[0, 0, 0]);
        assert_eq!(&encoded[18..26], &[8, 7, 6, 5, 4, 3, 2, 1]);
        assert_eq!(&encoded[26..41], &[0; 15]);
        let record = record_at(&section, 0);
        assert_eq!(record.items[0].vnum, 0x0506_0708);
        assert_eq!(record.items[0].count, 0x090a);
        assert_eq!(record.items[0].pos, ShopItemPosition::new(0, 0));
        assert_eq!(record.items[0].price, 0x0102_0304_0506_0708);
        assert_eq!(record.items[0].price_type, 21); // The query supplied this byte.
    }
}
