#ifndef __INC_METIN2_ITEM_LENGTH_H__
#define __INC_METIN2_ITEM_LENGTH_H__

#include "prodomodefines.h"

enum EItemMisc
{
	ITEM_NAME_MAX_LEN			= 36,
	ITEM_VALUES_MAX_NUM			= 6,
	ITEM_SMALL_DESCR_MAX_LEN	= 256,
	ITEM_LIMIT_MAX_NUM			= 2,
	ITEM_APPLY_MAX_NUM			= 3,
#ifdef ENABLE_EXTENDED_SOCKETS
	ITEM_SOCKET_MAX_NUM			= 6,
	ITEM_STONES_MAX_NUM 		= 3, //If you are extending stones in item, change to 6. If you do not want more than 3 stones, keep 3.(git)
#else
	ITEM_SOCKET_MAX_NUM			= 3,
#endif
	ITEM_MAX_COUNT				= 5000,

	ITEM_ATTRIBUTE_NORM_NUM		= 5,
	ITEM_ATTRIBUTE_RARE_NUM		= 2,

	ITEM_ATTRIBUTE_NORM_START	= 0,
	ITEM_ATTRIBUTE_NORM_END		= ITEM_ATTRIBUTE_NORM_START + ITEM_ATTRIBUTE_NORM_NUM,

	ITEM_ATTRIBUTE_RARE_START	= ITEM_ATTRIBUTE_NORM_END,
	ITEM_ATTRIBUTE_RARE_END		= ITEM_ATTRIBUTE_RARE_START + ITEM_ATTRIBUTE_RARE_NUM,

	ITEM_ATTRIBUTE_MAX_NUM		= ITEM_ATTRIBUTE_RARE_END, // 7
#ifdef ENABLE_SWITCHBOT
	MAX_NORM_ATTR_NUM			= 5,
	MAX_RARE_ATTR_NUM			= 2,
#endif
	ITEM_ATTRIBUTE_MAX_LEVEL	= 5,
	ITEM_AWARD_WHY_MAX_LEN		= 50,

	REFINE_MATERIAL_MAX_NUM		= 5,

	ITEM_ELK_VNUM				= 50026,
	
	// ITEM_TOGGLE items:
	// Unique group, or -1 if unlimited simultaneously active items
	ITEM_VALUE_TOGGLE_GROUP = 5,
	
	ITEM_SOCKET_UNIQUE_SAVE_TIME = ITEM_SOCKET_MAX_NUM - 2,
	ITEM_SOCKET_UNIQUE_REMAIN_TIME = ITEM_SOCKET_MAX_NUM - 1,
	
	// ITEM_TOGGLE items
	ITEM_SOCKET_TOGGLE_TIME = 0,
	ITEM_SOCKET_TOGGLE_ACTIVE = 3,
	ITEM_SOCKET_TOGGLE_RIDING = 4,
};

const BYTE ITEM_SOCKET_REMAIN_SEC = 0;
enum EItemValueIdice
{
	ITEM_VALUE_DRAGON_SOUL_POLL_OUT_BONUS_IDX = 0,
	ITEM_VALUE_CHARGING_AMOUNT_IDX = 0,
	ITEM_VALUE_SECONDARY_COIN_UNIT_IDX = 0,
};
enum EItemDragonSoulSockets
{
	ITEM_SOCKET_DRAGON_SOUL_ACTIVE_IDX = 2,
	ITEM_SOCKET_CHARGING_AMOUNT_IDX = 2,
};

enum EItemTypes
{
    ITEM_NONE,              //0
    ITEM_WEAPON,            //1//����
    ITEM_ARMOR,             //2//����
    ITEM_USE,               //3//������ ���
    ITEM_AUTOUSE,           //4
    ITEM_MATERIAL,          //5
    ITEM_SPECIAL,           //6 //����� ������
    ITEM_TOOL,              //7
    ITEM_LOTTERY,           //8//����
    ITEM_ELK,               //9//��
    ITEM_METIN,             //10
    ITEM_CONTAINER,         //11
    ITEM_FISH,              //12//����
    ITEM_ROD,               //13
    ITEM_RESOURCE,          //14
    ITEM_CAMPFIRE,          //15
    ITEM_UNIQUE,            //16
    ITEM_SKILLBOOK,         //17
    ITEM_QUEST,             //18
    ITEM_POLYMORPH,         //19
    ITEM_TREASURE_BOX,      //20//��������
    ITEM_TREASURE_KEY,      //21//�������� ����
    ITEM_SKILLFORGET,       //22
    ITEM_GIFTBOX,           //23
    ITEM_PICK,              //24
    ITEM_HAIR,              //25//�Ӹ�
    ITEM_TOTEM,             //26//����
	ITEM_BLEND,				//27//�����ɶ� �����ϰ� �Ӽ��� �ٴ� �๰
	ITEM_COSTUME,			//28//�ڽ��� ������ (2011�� 8�� �߰��� �ڽ��� �ý��ۿ� ������)
	ITEM_DS,				//29 //��ȥ��
	ITEM_SPECIAL_DS,		//30 // Ư���� ��ȥ�� (DS_SLOT�� �����ϴ� UNIQUE �������̶� �����ϸ� ��)
	ITEM_EXTRACT,			//31 ���⵵��.
	ITEM_SECONDARY_COIN,	//32 ?? ������??
	ITEM_RING,				//33 ����
	ITEM_BELT,				//34 ��Ʈ
	ITEM_TALISMAN,			//35
	ITEM_TOGGLE,			//36
};

enum EMetinSubTypes
{
	METIN_NORMAL,
	METIN_GOLD,
};


enum EToggleSubTypes
{
	TOGGLE_SHAMAN,

};

enum EWeaponSubTypes
{
	WEAPON_SWORD,
	WEAPON_DAGGER,
	WEAPON_BOW,
	WEAPON_TWO_HANDED,
	WEAPON_BELL,
	WEAPON_FAN,
	WEAPON_ARROW,
	WEAPON_MOUNT_SPEAR,
	WEAPON_NUM_TYPES,
};

enum EArmorSubTypes
{
	ARMOR_BODY,
	ARMOR_HEAD,
	ARMOR_SHIELD,
	ARMOR_WRIST,
	ARMOR_FOOTS,
	ARMOR_NECK,
	ARMOR_EAR,
#ifdef ENABLE_GLOVE_SYSTEM
	ARMOR_GLOVE,
#endif
	ARMOR_NUM_TYPES
};

enum ECostumeSubTypes
{
	COSTUME_BODY = ARMOR_BODY,			// [�߿�!!] ECostumeSubTypes enum value��  �������� EArmorSubTypes�� �װͰ� ���ƾ� ��.
	COSTUME_HAIR = ARMOR_HEAD,			// �̴� �ڽ��� �����ۿ� �߰� �Ӽ��� ���̰ڴٴ� ������� ��û�� ���� ���� ������ Ȱ���ϱ� ������.
#ifdef ENABLE_MOUNT_COSTUME_SYSTEM
	COSTUME_MOUNT	= 2,
#endif
#ifdef __SASH_SYSTEM__
	COSTUME_SASH	= 3,
#endif
#ifdef ENABLE_WEAPON_COSTUME_SYSTEM
	COSTUME_WEAPON	= 4,
#endif
#ifdef __AURA_SYSTEM__
	COSTUME_AURA	= 5,
#endif
#ifdef ENABLE_PET_COSTUME_SYSTEM
	COSTUME_PET     = 6,
#endif
	COSTUME_SASH_SKIN,
	COSTUME_NUM_TYPES,
};

enum EDragonSoulSubType
{
	DS_SLOT1,
	DS_SLOT2,
	DS_SLOT3,
	DS_SLOT4,
	DS_SLOT5,
	DS_SLOT6,
	DS_SLOT_MAX,
};

enum EDragonSoulGradeTypes
{
	DRAGON_SOUL_GRADE_NORMAL,
	DRAGON_SOUL_GRADE_BRILLIANT,
	DRAGON_SOUL_GRADE_RARE,
	DRAGON_SOUL_GRADE_ANCIENT,
	DRAGON_SOUL_GRADE_LEGENDARY,
	#ifdef ENABLE_DRAGONSOUL_ALCHEMY_PLUS
	DRAGON_SOUL_GRADE_MYTHIC,
#endif
	DRAGON_SOUL_GRADE_MAX,

};

enum EDragonSoulStepTypes
{
	DRAGON_SOUL_STEP_LOWEST,
	DRAGON_SOUL_STEP_LOW,
	DRAGON_SOUL_STEP_MID,
	DRAGON_SOUL_STEP_HIGH,
	DRAGON_SOUL_STEP_HIGHEST,
	DRAGON_SOUL_STEP_MAX,
};
#define DRAGON_SOUL_STRENGTH_MAX 7

enum EDSInventoryMaxNum
{
	DRAGON_SOUL_INVENTORY_MAX_NUM = DS_SLOT_MAX * DRAGON_SOUL_GRADE_MAX * DRAGON_SOUL_BOX_SIZE,
};

enum EFishSubTypes
{
	FISH_ALIVE,
	FISH_DEAD,
};

enum EBattlePassItem
{
	ITEM_BATTLE_PASS = 50027,
};

enum EResourceSubTypes
{
	RESOURCE_FISHBONE,
	RESOURCE_WATERSTONEPIECE,
	RESOURCE_WATERSTONE,
	RESOURCE_BLOOD_PEARL,
	RESOURCE_BLUE_PEARL,
	RESOURCE_WHITE_PEARL,
	RESOURCE_BUCKET,
	RESOURCE_CRYSTAL,
	RESOURCE_GEM,
	RESOURCE_STONE,
	RESOURCE_METIN,
	RESOURCE_ORE,
#ifdef __AURA_SYSTEM__
	RESOURCE_AURA,
#endif
};

enum EUniqueSubTypes
{
	UNIQUE_NONE,
	UNIQUE_BOOK,
	UNIQUE_SPECIAL_RIDE,
	UNIQUE_SPECIAL_MOUNT_RIDE,
};

enum EUseSubTypes
{
	USE_POTION,					// 0
	USE_TALISMAN,
	USE_TUNING,
	USE_MOVE,
	USE_TREASURE_BOX,
	USE_MONEYBAG,
	USE_BAIT,
	USE_ABILITY_UP,
	USE_AFFECT,
	USE_CREATE_STONE,
	USE_SPECIAL,				// 10
	USE_POTION_NODELAY,
	USE_CLEAR,
	USE_INVISIBILITY,
	USE_DETACHMENT,
	USE_BUCKET,
	USE_POTION_CONTINUE,
	USE_CLEAN_SOCKET,
	USE_CHANGE_ATTRIBUTE,
	USE_ADD_ATTRIBUTE,
	USE_ADD_ACCESSORY_SOCKET,	// 20
	USE_PUT_INTO_ACCESSORY_SOCKET,
	USE_ADD_ATTRIBUTE2,
	USE_RECIPE,
	USE_CHANGE_ATTRIBUTE2,
	USE_BIND,
	USE_UNBIND,
	USE_TIME_CHARGE_PER,
	USE_TIME_CHARGE_FIX,				// 28
	USE_PUT_INTO_BELT_SOCKET,			// 29 ��Ʈ ���Ͽ� ����� �� �ִ� ������
	USE_PUT_INTO_RING_SOCKET,			// 30 ���� ���Ͽ� ����� �� �ִ� ������ (����ũ ���� ����, ���� �߰��� ���� ����)
	USE_CHANGE_COSTUME_ATTR,			// 31
	USE_RESET_COSTUME_ATTR,				// 32
	USE_UNK33, // 33 
	USE_CHANGE_ATTRIBUTE_PLUS, // 34
#ifdef __AURA_SYSTEM__
	USE_PUT_INTO_AURA_SOCKET,			// 35 AURA_BOOSTER
#endif
#ifdef ENABLE_REFINE_ELEMENT
	USE_ELEMENT_UPGRADE, // 36
	USE_ELEMENT_DOWNGRADE, // 37
	USE_ELEMENT_CHANGE, // 38
#endif
	USE_SET_ATT_COSTUME, // 39
	USE_SET_ATT_PET, // 40
	USE_SET_ATT_MOUNT, // 41
	USE_SET_ATT_COSTUME_WEAPON, // 42
	USE_ADD_ATTRIBUTE_TALISMAN, // 43 talisman attr
	USE_CHANGE_ATTRIBUTE_TALISMAN, // 44 talisman attr
	USE_ADD_ATTRIBUTE_GLOVE, // 45 glove attr
	USE_CHANGE_ATTRIBUTE_GLOVE, // 46 glove attr
#ifdef __ENABLE_SHAMAN_SYSTEM__
	USE_UNLOCK_SHAMAN, // 47
#endif
};

enum EExtractSubTypes
{
	EXTRACT_DRAGON_SOUL,
	EXTRACT_DRAGON_HEART,
};

enum EAutoUseSubTypes
{
	AUTOUSE_POTION,
	AUTOUSE_ABILITY_UP,
	AUTOUSE_BOMB,
	AUTOUSE_GOLD,
	AUTOUSE_MONEYBAG,
	AUTOUSE_TREASURE_BOX
};

enum EMaterialSubTypes
{
	MATERIAL_LEATHER,
	MATERIAL_BLOOD,
	MATERIAL_ROOT,
	MATERIAL_NEEDLE,
	MATERIAL_JEWEL,
	MATERIAL_DS_REFINE_NORMAL,
	MATERIAL_DS_REFINE_BLESSED,
	MATERIAL_DS_REFINE_HOLLY,
};

enum ESpecialSubTypes
{
	SPECIAL_MAP,
	SPECIAL_KEY,
	SPECIAL_DOC,
	SPECIAL_SPIRIT,
};

enum EToolSubTypes
{
	TOOL_FISHING_ROD
};

enum ELotterySubTypes
{
	LOTTERY_TICKET,
	LOTTERY_INSTANT
};

enum EItemFlag
{
	ITEM_FLAG_REFINEABLE		= (1 << 0),
	ITEM_FLAG_SAVE			= (1 << 1),
	ITEM_FLAG_STACKABLE		= (1 << 2),	// ������ ��ĥ �� ����
	ITEM_FLAG_COUNT_PER_1GOLD	= (1 << 3),
	ITEM_FLAG_SLOW_QUERY		= (1 << 4),
	ITEM_FLAG_UNUSED01		= (1 << 5),	// UNUSED
	ITEM_FLAG_UNIQUE		= (1 << 6),
	ITEM_FLAG_MAKECOUNT		= (1 << 7),
	ITEM_FLAG_IRREMOVABLE		= (1 << 8),
	ITEM_FLAG_CONFIRM_WHEN_USE	= (1 << 9),
	ITEM_FLAG_QUEST_USE		= (1 << 10),
	ITEM_FLAG_QUEST_USE_MULTIPLE	= (1 << 11),
	ITEM_FLAG_QUEST_GIVE		= (1 << 12),
	ITEM_FLAG_LOG			= (1 << 13),
	ITEM_FLAG_APPLICABLE		= (1 << 14),
};

enum EItemAntiFlag
{
	ITEM_ANTIFLAG_FEMALE	= (1 << 0), // ���� ��� �Ұ�
	ITEM_ANTIFLAG_MALE		= (1 << 1), // ���� ��� �Ұ�
	ITEM_ANTIFLAG_WARRIOR	= (1 << 2), // ���� ��� �Ұ�
	ITEM_ANTIFLAG_ASSASSIN	= (1 << 3), // �ڰ� ��� �Ұ�
	ITEM_ANTIFLAG_SURA		= (1 << 4), // ���� ��� �Ұ�
	ITEM_ANTIFLAG_SHAMAN	= (1 << 5), // ���� ��� �Ұ�
	ITEM_ANTIFLAG_GET		= (1 << 6), // ���� �� ����
	ITEM_ANTIFLAG_DROP		= (1 << 7), // ���� �� ����
	ITEM_ANTIFLAG_SELL		= (1 << 8), // �� �� ����
	ITEM_ANTIFLAG_EMPIRE_A	= (1 << 9), // A ���� ��� �Ұ�
	ITEM_ANTIFLAG_EMPIRE_B	= (1 << 10), // B ���� ��� �Ұ�
	ITEM_ANTIFLAG_EMPIRE_C	= (1 << 11), // C ���� ��� �Ұ�
	ITEM_ANTIFLAG_SAVE		= (1 << 12), // ������� ����
	ITEM_ANTIFLAG_GIVE		= (1 << 13), // �ŷ� �Ұ�
	ITEM_ANTIFLAG_PKDROP	= (1 << 14), // PK�� �������� ����
	ITEM_ANTIFLAG_STACK		= (1 << 15), // ��ĥ �� ����
	ITEM_ANTIFLAG_MYSHOP	= (1 << 16), // ���� ������ �ø� �� ����
	ITEM_ANTIFLAG_SAFEBOX	= (1 << 17), // â���� ���� �� ����
};

enum EItemWearableFlag
{
	WEARABLE_BODY	= (1 << 0),
	WEARABLE_HEAD	= (1 << 1),
	WEARABLE_FOOTS	= (1 << 2),
	WEARABLE_WRIST	= (1 << 3),
	WEARABLE_WEAPON	= (1 << 4),
	WEARABLE_NECK	= (1 << 5),
	WEARABLE_EAR	= (1 << 6),
	WEARABLE_UNIQUE	= (1 << 7),
	WEARABLE_SHIELD	= (1 << 8),
	WEARABLE_ARROW	= (1 << 9),
	WEARABLE_HAIR	= (1 << 10),
	WEARABLE_ABILITY = (1 << 11),
#ifdef __SASH_SYSTEM__
	WEARABLE_COSTUME_SASH = (1 << 12),
#endif
	WEARABLE_FIRE	= (1 << 13),
	WEARABLE_ICE	= (1 << 14),
	WEARABLE_EARTH	= (1 << 15),
	WEARABLE_DARK	= (1 << 16),
	WEARABLE_WIND	= (1 << 17),
	WEARABLE_ELEC	= (1 << 18),
#ifdef ENABLE_GLOVE_SYSTEM
	WEARABLE_GLOVE  = (1 << 19),
#endif
	WEARABLE_SASH_SKIN  = (1 << 20),
};

enum ELimitTypes
{
	LIMIT_NONE,

	LIMIT_LEVEL,
	LIMIT_STR,
	LIMIT_DEX,
	LIMIT_INT,
	LIMIT_CON,

	/// ���� ���ο� ��� ���� �ǽð����� �ð� ���� (socket0�� �Ҹ� �ð��� ����: unix_timestamp Ÿ��)
	LIMIT_REAL_TIME,

	/// �������� �� ó�� ���(Ȥ�� ����) �� �������� ����Ÿ�� Ÿ�̸� ����
	/// ���� ��� ������ socket0�� ��밡�ɽð�(�ʴ���, 0�̸� �������� limit value�� ���) ���� �����ִٰ�
	/// ������ ���� socket1�� ��� Ƚ���� ������ socket0�� unix_timestamp Ÿ���� �Ҹ�ð��� ����.
	LIMIT_REAL_TIME_START_FIRST_USE,

	/// �������� ���� ���� ���� ��� �ð��� �����Ǵ� ������
	/// socket0�� ���� �ð��� �ʴ����� ����. (������ ���� ���� �ش� ���� 0�̸� �������� limit value���� socket0�� ����)
	LIMIT_TIMER_BASED_ON_WEAR,
	LIMIT_CHAMPION,

	LIMIT_MAX_NUM
};

enum EAttrAddonTypes
{
	ATTR_ADDON_NONE,
	// positive values are reserved for set
	ATTR_DAMAGE_ADDON = -1,
};

enum ERefineType
{
	REFINE_TYPE_NORMAL,
	REFINE_TYPE_NOT_USED1,
	REFINE_TYPE_SCROLL,
	REFINE_TYPE_HYUNIRON,
	REFINE_TYPE_MONEY_ONLY,
	REFINE_TYPE_MUSIN,
	REFINE_TYPE_BDRAGON,
};
#ifdef __AURA_SYSTEM__
enum EItemAuraSockets
{
	ITEM_SOCKET_AURA_DRAIN_ITEM_VNUM,
	ITEM_SOCKET_AURA_CURRENT_LEVEL,
	ITEM_SOCKET_AURA_BOOST,
};

enum EItemAuraMaterialValues
{
	ITEM_AURA_MATERIAL_EXP_VALUE,
};

enum EItemAuraBoostValues
{
	ITEM_AURA_BOOST_PERCENT_VALUE,
	ITEM_AURA_BOOST_TIME_VALUE,
	ITEM_AURA_BOOST_UNLIMITED_VALUE,
};

enum EItemAuraBoostIndex
{
	ITEM_AURA_BOOST_ERASER,
	ITEM_AURA_BOOST_WEAK,
	ITEM_AURA_BOOST_NORMAL,
	ITEM_AURA_BOOST_STRONG,
	ITEM_AURA_BOOST_ULTIMATE,
	ITEM_AURA_BOOST_MAX,
};
#endif
#ifdef __SASH_SYSTEM__
enum ESashInfo
{
	SASH_GRADE_VALUE_FIELD = 0,
	SASH_ABSORPTION_SOCKET = 0,
	SASH_ABSORBED_SOCKET = 1,
	SASH_GRADE_1_ABS = 1,
	SASH_GRADE_2_ABS = 5,
	SASH_GRADE_3_ABS = 10,
	SASH_GRADE_4_ABS_MIN = 11,
	SASH_GRADE_4_ABS_MAX = 25,
	SASH_GRADE_4_ABS_MAX_COMB = 19,
	SASH_GRADE_4_ABS_RANGE = 5,
	SASH_EFFECT_FROM_ABS = 19,
	SASH_CLEAN_ATTR_VALUE0 = 7,
	SASH_WINDOW_MAX_MATERIALS = 2,
	SASH_GRADE_1_PRICE = 100000,
	SASH_GRADE_2_PRICE = 200000,
	SASH_GRADE_3_PRICE = 300000,
	SASH_GRADE_4_PRICE = 500000,
	SASH_COMBINE_GRADE_1 = 80,
	SASH_COMBINE_GRADE_2 = 70,
	SASH_COMBINE_GRADE_3 = 50,
	SASH_COMBINE_GRADE_4 = 30,
};
#endif

#endif
