#ifndef __INC_METIN_II_LENGTH_H__
#define __INC_METIN_II_LENGTH_H__

#include "prodomodefines.h"

#define WORD_MAX 0xffff
enum EMisc
{
	MAX_HOST_LENGTH			= 15,
	IP_ADDRESS_LENGTH		= 15,
	LOGIN_MAX_LEN			= 30,
	PASSWD_MAX_LEN			= 16,
	PLAYER_PER_ACCOUNT		= 4,
	ACCOUNT_STATUS_MAX_LEN	= 8,
	CHARACTER_NAME_MAX_LEN	= 24,
	SHOP_SIGN_MAX_LEN		= 32,
	INVENTORY_PAGE_COLUMN	= 5, // 5 (default)
	INVENTORY_PAGE_ROW		= 9, // 9 (default)
	INVENTORY_PAGE_SIZE		= INVENTORY_PAGE_COLUMN*INVENTORY_PAGE_ROW,
#ifdef ENABLE_EXTEND_INVEN_SYSTEM
	INVENTORY_PAGE_COUNT	= 4, // 2 (default)
#else
	INVENTORY_PAGE_COUNT	= 2, // 2 (default)
#endif
	INVENTORY_MAX_NUM		= INVENTORY_PAGE_SIZE*INVENTORY_PAGE_COUNT, // 90 (default)
	
#ifdef ENABLE_CUSTOM_INVENTORY
	CUSTOM_INVENTORY_PAGE_SIZE = 45,
	CUSTOM_INVENTORY_PAGE_COUNT = 4,
	CUSTOM_INVENTORY_MAX_NUM = CUSTOM_INVENTORY_PAGE_SIZE * CUSTOM_INVENTORY_PAGE_COUNT,
	CUSTOM_INVENTORY_CATEGORY_NUM = 6,
#endif
	
	ABILITY_MAX_NUM			= 50,
#ifdef __ENABLE_INVENTORY_PROTECTED_SYSTEM__
	INVENTORY_PROTECTED_PASSWORD_MAX_LEN = 6,
#endif
	EMPIRE_MAX_NUM			= 4,
	BANWORD_MAX_LEN			= 24,
	SOCIAL_ID_MAX_LEN		= 18,

	GUILD_NAME_MAX_LEN		= 12,
	QUEST_NAME_MAX_NUM		= 64,
	SHOP_HOST_ITEM_MAX_NUM	= 40,
	SHOP_GUEST_ITEM_MAX_NUM = 18,

	SHOP_PRICELIST_MAX_NUM	= 40,

	CHAT_MAX_LEN			= 512,

	QUICKSLOT_MAX_NUM		= 36,

	JOURNAL_MAX_NUM			= 2,

	QUERY_MAX_LEN			= 8192,

	FILE_MAX_LEN			= 128,

	PLAYER_EXP_TABLE_MAX	= 120,
	PLAYER_MAX_LEVEL_CONST	= 250,

#if defined(__CONQUEROR_LEVEL__)
	PLAYER_CONQUEROR_EXP_TABLE_MAX = 30,
	PLAYER_MAX_CONQUEROR_LEVEL_CONST = 30,
#endif

	GUILD_MAX_LEVEL			= 20,
	MOB_MAX_LEVEL			= 100,

	ATTRIBUTE_MAX_VALUE		= 20,
	CHARACTER_PATH_MAX_NUM	= 64,
	SKILL_MAX_NUM			= 255,
	SKILLBOOK_DELAY_MIN		= 64800,
	SKILLBOOK_DELAY_MAX		= 108000,
	SKILL_MAX_LEVEL			= 40,

	APPLY_NAME_MAX_LEN		= 32,
	EVENT_FLAG_NAME_MAX_LEN = 32,

	MOB_SKILL_MAX_NUM		= 5,

    POINT_MAX_NUM = 255,
	DRAGON_SOUL_BOX_SIZE = 32,
	DRAGON_SOUL_BOX_COLUMN_NUM = 8,
	DRAGON_SOUL_BOX_ROW_NUM = DRAGON_SOUL_BOX_SIZE / DRAGON_SOUL_BOX_COLUMN_NUM,
	DRAGON_SOUL_REFINE_GRID_SIZE = 15,
	MAX_AMOUNT_OF_MALL_BONUS	= 20,

	WEAR_MAX_NUM				= 64,
	
#if defined(__EXTENDED_SAFEBOX__)
	SAFEBOX_MAX_PAGE_COUNT		= 6,
	SAFEBOX_MAX_NUM				= 45 * SAFEBOX_MAX_PAGE_COUNT,
#endif
	//LIMIT_GOLD
	// GOLD_MAX = 1000000000000001LL,
	//END_LIMIT_GOLD

#ifdef ENABLE_REMOVE_LIMIT_GOLD
	GOLD_MAX_MAX = 1200000000000000000ULL,
#endif

#ifdef ENABLE_GAYA_SYSTEM
GAYA_MAX = 999999,
#endif



#ifdef ENABLE_FISH_EVENT
	FISH_EVENT_SLOTS_NUM 		= 24,
	ITEM_FISH_EVENT_BOX			= 25106,
	ITEM_FISH_EVENT_BOX_SPECIAL	= 25107,
#endif

	SHOP_TAB_NAME_MAX = 32,
	SHOP_TAB_COUNT_MAX = 7,

	BELT_INVENTORY_SLOT_WIDTH = 4,
	BELT_INVENTORY_SLOT_HEIGHT= 4,

	BELT_INVENTORY_SLOT_COUNT = BELT_INVENTORY_SLOT_WIDTH * BELT_INVENTORY_SLOT_HEIGHT,
};

#ifdef __PREMIUM_PRIVATE_SHOP__
enum EPrivateShop
{
	INVENTORY_PAGE_MAX_NUM			= INVENTORY_PAGE_COUNT,
	INVENTORY_PAGE_WIDTH			= 5,
	INVENTORY_PAGE_HEIGHT			= 9,
	INVENTORY_PAGE_ITEM_MAX_NUM		= INVENTORY_PAGE_WIDTH * INVENTORY_PAGE_HEIGHT,

	PRIVATE_SHOP_PAGE_MAX_NUM		= 2,
	PRIVATE_SHOP_WIDTH				= 8,
	PRIVATE_SHOP_HEIGHT				= 8,
	PRIVATE_SHOP_PAGE_ITEM_MAX_NUM	= PRIVATE_SHOP_WIDTH * PRIVATE_SHOP_HEIGHT,
	PRIVATE_SHOP_HOST_ITEM_MAX_NUM	= (PRIVATE_SHOP_WIDTH * PRIVATE_SHOP_HEIGHT) * PRIVATE_SHOP_PAGE_MAX_NUM,
	PRIVATE_SHOP_LOCKED_SLOT_MAX_NUM = PRIVATE_SHOP_HOST_ITEM_MAX_NUM / 2,
	PRIVATE_SHOP_SLOT_UNLOCK_ITEM = 72357,
	PRIVATE_SHOP_MAX_PREMIUM_TIME = 3600 * 24 * 7,
	SELECTED_ITEM_MAX_NUM = 10,

	VALID_SALE_DAY_INTERVAL					= 30,
	VALID_MARKET_PRICE_DAY_INTERVAL			= 3,
	MARKET_ITEM_PRICE_UPDATE_SEC_INTERVAL	= 3600,

	TITLE_MAX_LEN = 32,
	TITLE_MIN_LEN = 3,
};

enum EShopSearchMode
{
	MODE_NONE,
	MODE_LOOKING,
	MODE_TRADING,
};

enum EPrivateShopState
{
	STATE_UNAVAILABLE,
	STATE_CLOSED,
	STATE_OPEN,
	STATE_MODIFY
};

enum EPrivateShopSearchState
{
	STATE_NON_EXISTENT,
	STATE_REMOVED,
	STATE_AVAILABLE,
	STATE_RESTRICTED,
};
#endif


#ifdef __CHANGELOOK_SYSTEM__
enum EChangeLookInfo
{
	CL_WINDOW_MAX_MATERIALS = 2,
	CL_CLEAN_ATTR_VALUE0 = 8,
	CL_TRANSMUTATION_PRICE = 50000000,
};
#endif

#ifdef ENABLE_FISH_EVENT
enum EFishEventInfo
{
	FISH_EVENT_SHAPE_NONE,
	FISH_EVENT_SHAPE_1,
	FISH_EVENT_SHAPE_2,
	FISH_EVENT_SHAPE_3,
	FISH_EVENT_SHAPE_4,
	FISH_EVENT_SHAPE_5,
	FISH_EVENT_SHAPE_6,
	FISH_EVENT_SHAPE_7,
	FISH_EVENT_SHAPE_MAX_NUM,
};
#endif

#if defined(__ATTR_6TH_7TH__)
enum EAttr67Add
{
	ATTR67_ADD_SLOT_MAX = 1,
	ATTR67_MATERIAL_MAX_COUNT = 10,
	ATTR67_SUPPORT_MAX_COUNT = 5,
	ATTR67_SUCCESS_PER_MATERIAL = 2,
	ATTR67_ADD_WAIT_TIME = 60 * 60 * 24,
};
#endif

enum EWearPositions
{
	WEAR_BODY,		// 0
	WEAR_HEAD,		// 1
	WEAR_FOOTS,		// 2
	WEAR_WRIST,		// 3
	WEAR_WEAPON,	// 4
	WEAR_NECK,		// 5
	WEAR_EAR,		// 6
	WEAR_UNIQUE1,	// 7
	WEAR_UNIQUE2,	// 8
	WEAR_ARROW,		// 9
	WEAR_SHIELD,	// 10
    WEAR_ABILITY1,  // 11
    WEAR_ABILITY2,  // 12
    WEAR_ABILITY3,  // 13
    WEAR_ABILITY4,  // 14
    WEAR_ABILITY5,  // 15
    WEAR_ABILITY6,  // 16
    WEAR_ABILITY7,  // 17
    WEAR_ABILITY8,  // 18
	WEAR_COSTUME_BODY,	// 19
	WEAR_COSTUME_HAIR,	// 20
	WEAR_COSTUME_MOUNT, // 21
	WEAR_COSTUME_WEAPON, // 22
	WEAR_COSTUME_SASH, // 23
	WEAR_COSTUME_AURA, //24
	
	WEAR_RING1,			// 25
	WEAR_RING2,			// 26
	WEAR_BELT,			// 27
	
	WEAR_COSTUME_PET,	// 28
	WEAR_COSTUME_SASH_SKIN,
	
	WEAR_TALISMAN_FIRE,
	WEAR_TALISMAN_ICE,
	WEAR_TALISMAN_EARTH,
	WEAR_TALISMAN_DARK,
	WEAR_TALISMAN_WIND,
	WEAR_TALISMAN_ELEC,
	
#ifdef ENABLE_GLOVE_SYSTEM
	WEAR_GLOVE,
#endif

	WEAR_MAX = 64	//
};

enum EDragonSoulDeckType
{
	DRAGON_SOUL_DECK_0,
	DRAGON_SOUL_DECK_1,
	DRAGON_SOUL_DECK_MAX_NUM = 2,

	DRAGON_SOUL_DECK_RESERVED_MAX_NUM = 3,
};

enum ESex
{
	SEX_MALE,
	SEX_FEMALE
};

#ifdef ENABLE_EXTEND_INVEN_SYSTEM
enum EInventory
{
	/* you can change */
	INVENTORY_OPEN_PAGE_COUNT = 2,
	INVENTORY_OPEN_KEY_VNUM = 72319,
	INVENTORY_OPEN_KEY_VNUM2 = 72320,
	INVENTORY_START_DELETE_VNUM = INVENTORY_OPEN_KEY_VNUM, // start deleting from a tradeable item
	INVENTORY_NEED_KEY_START = 2,
	INVENTORY_NEED_KEY_INCREASE = 3, // Increase the number of keys in each 3 stages. you can change
	/* end */
	INVENTORY_WIDTH = 5,
	INVENTORY_HEIGHT = 9,
	//INVENTORY_PAGE_SIZE = INVENTORY_WIDTH*INVENTORY_HEIGHT,
	//INVENTORY_PAGE_COUNT = INVENTORY_MAX_NUM / INVENTORY_PAGE_SIZE,
	INVENTORY_OPEN_PAGE_SIZE = INVENTORY_OPEN_PAGE_COUNT*INVENTORY_PAGE_SIZE,
	INVENTORY_LOCKED_PAGE_COUNT = INVENTORY_PAGE_COUNT-INVENTORY_OPEN_PAGE_COUNT,
	INVENTORY_LOCK_COVER_COUNT = INVENTORY_LOCKED_PAGE_COUNT*INVENTORY_HEIGHT
};
#endif

enum EDirection
{
	DIR_NORTH,
	DIR_NORTHEAST,
	DIR_EAST,
	DIR_SOUTHEAST,
	DIR_SOUTH,
	DIR_SOUTHWEST,
	DIR_WEST,
	DIR_NORTHWEST,
	DIR_MAX_NUM
};

#define ABILITY_MAX_LEVEL	10  /* ��� �ִ� ���� */

enum EAbilityDifficulty
{
	DIFFICULTY_EASY,
	DIFFICULTY_NORMAL,
	DIFFICULTY_HARD,
	DIFFICULTY_VERY_HARD,
	DIFFICULTY_NUM_TYPES
};

enum EAbilityCategory
{
	CATEGORY_PHYSICAL,	/* ��ü�� �����Ƽ */
	CATEGORY_MENTAL,	/* ������ �����Ƽ */
	CATEGORY_ATTRIBUTE,	/* �ɷ� �����Ƽ */
	CATEGORY_NUM_TYPES
};

enum EJobs
{
	JOB_WARRIOR,
	JOB_ASSASSIN,
	JOB_SURA,
	JOB_SHAMAN,
	JOB_MAX_NUM
};

enum ESkillGroups
{
	SKILL_GROUP_MAX_NUM = 2,
};

enum ERaceFlags
{
	RACE_FLAG_ANIMAL	= (1 << 0),
	RACE_FLAG_UNDEAD	= (1 << 1),
	RACE_FLAG_DEVIL		= (1 << 2),
	RACE_FLAG_HUMAN		= (1 << 3),
	RACE_FLAG_ORC		= (1 << 4),
	RACE_FLAG_MILGYO	= (1 << 5),
	RACE_FLAG_INSECT	= (1 << 6),
	RACE_FLAG_FIRE		= (1 << 7),
	RACE_FLAG_ICE		= (1 << 8),
	RACE_FLAG_DESERT	= (1 << 9),
	RACE_FLAG_TREE		= (1 << 10),
	RACE_FLAG_ATT_ELEC	= (1 << 11),
	RACE_FLAG_ATT_FIRE	= (1 << 12),
	RACE_FLAG_ATT_ICE	= (1 << 13),
	RACE_FLAG_ATT_WIND	= (1 << 14),
	RACE_FLAG_ATT_EARTH	= (1 << 15),
	RACE_FLAG_ATT_DARK	= (1 << 16),
	RACE_FLAG_METIN		= (1 << 17),
	RACE_FLAG_BOSS		= (1 << 18),
	RACE_FLAG_CZ		= (1 << 19),
};

enum ELoads
{
	LOAD_NONE,
	LOAD_LIGHT,
	LOAD_NORMAL,
	LOAD_HEAVY,
	LOAD_MASSIVE
};

enum
{
	QUICKSLOT_TYPE_NONE,
	QUICKSLOT_TYPE_ITEM,
	QUICKSLOT_TYPE_SKILL,
	QUICKSLOT_TYPE_COMMAND,
	QUICKSLOT_TYPE_MAX_NUM,
};

enum EParts
{
	PART_MAIN,
	PART_WEAPON,
	PART_HEAD,
	PART_HAIR,
	PART_SASH,
	PART_AURA,
	PART_MAX_NUM,
	PART_WEAPON_SUB,
};

enum EEmpire
{
	ALL_EMPIRES,
	SHINSOO_EMPIRE,
	CHUNJO_EMPIRE,
	JINNO_EMPIRE
};

enum EChatType
{
	CHAT_TYPE_TALKING,
	CHAT_TYPE_INFO,
	CHAT_TYPE_NOTICE,
	CHAT_TYPE_PARTY,
	CHAT_TYPE_GUILD,
	CHAT_TYPE_COMMAND,
	CHAT_TYPE_SHOUT,
	CHAT_TYPE_WHISPER,
	CHAT_TYPE_BIG_NOTICE,
	CHAT_TYPE_MONARCH_NOTICE,
#ifdef ENABLE_DICE_SYSTEM
	CHAT_TYPE_DICE_INFO, //11
#endif
	CHAT_TYPE_MAX_NUM
};

enum EWhisperType
{
	WHISPER_TYPE_NORMAL		= 0,
	WHISPER_TYPE_NOT_EXIST		= 1,
	WHISPER_TYPE_TARGET_BLOCKED	= 2,
	WHISPER_TYPE_SENDER_BLOCKED	= 3,
	WHISPER_TYPE_ERROR		= 4,
	WHISPER_TYPE_GM			= 5,
#if defined(OFFLINE_MESSAGE_REWORKED)
	WHISPER_TYPE_OFFLINE	= 6,
#endif
	WHISPER_TYPE_SYSTEM		= 0xFF
};

enum ECharacterPosition
{
	POSITION_GENERAL,
	POSITION_BATTLE,
	POSITION_DYING,
	POSITION_SITTING_CHAIR,
	POSITION_SITTING_GROUND,
	POSITION_INTRO,
	POSITION_MAX_NUM
};

enum EGMLevels
{
	GM_PLAYER,
	GM_LOW_WIZARD,
	GM_WIZARD,
	GM_HIGH_WIZARD,
	GM_GOD,
	GM_IMPLEMENTOR,
	GM_DISABLE,
};

enum EMobRank
{
	MOB_RANK_PAWN,
	MOB_RANK_S_PAWN,
	MOB_RANK_KNIGHT,
	MOB_RANK_S_KNIGHT,
	MOB_RANK_BOSS,
	MOB_RANK_KING,
	MOB_RANK_MAX_NUM
};

enum ECharType
{
	CHAR_TYPE_MONSTER,
	CHAR_TYPE_NPC,
	CHAR_TYPE_STONE,
	CHAR_TYPE_WARP,
	CHAR_TYPE_DOOR,
	CHAR_TYPE_BUILDING,
	CHAR_TYPE_PC,
	CHAR_TYPE_POLYMORPH_PC,
	CHAR_TYPE_HORSE,
	CHAR_TYPE_GOTO
};

enum EBattleType
{
	BATTLE_TYPE_MELEE,
	BATTLE_TYPE_RANGE,
	BATTLE_TYPE_MAGIC,
	BATTLE_TYPE_SPECIAL,
	BATTLE_TYPE_POWER,
	BATTLE_TYPE_TANKER,
	BATTLE_TYPE_SUPER_POWER,
	BATTLE_TYPE_SUPER_TANKER,
	BATTLE_TYPE_MAX_NUM
};

enum EApplyTypes
{
	APPLY_NONE,			// 0
	APPLY_MAX_HP,		// 1
	APPLY_MAX_SP,		// 2
	APPLY_CON,			// 3
	APPLY_INT,			// 4
	APPLY_STR,			// 5
	APPLY_DEX,			// 6
	APPLY_ATT_SPEED,	// 7
	APPLY_MOV_SPEED,	// 8
	APPLY_CAST_SPEED,	// 9
	APPLY_HP_REGEN,		// 10
	APPLY_SP_REGEN,		// 11
	APPLY_POISON_PCT,	// 12
	APPLY_STUN_PCT,		// 13
	APPLY_SLOW_PCT,		// 14
	APPLY_CRITICAL_PCT,		// 15
	APPLY_PENETRATE_PCT,	// 16
	APPLY_ATTBONUS_HUMAN,	// 17
	APPLY_ATTBONUS_ANIMAL,	// 18
	APPLY_ATTBONUS_ORC,		// 19
	APPLY_ATTBONUS_MILGYO,	// 20
	APPLY_ATTBONUS_UNDEAD,	// 21
	APPLY_ATTBONUS_DEVIL,	// 22
	APPLY_STEAL_HP,			// 23
	APPLY_STEAL_SP,			// 24
	APPLY_MANA_BURN_PCT,	// 25
	APPLY_DAMAGE_SP_RECOVER,// 26
	APPLY_BLOCK,			// 27
	APPLY_DODGE,			// 28
	APPLY_RESIST_SWORD,		// 29
	APPLY_RESIST_TWOHAND,	// 30
	APPLY_RESIST_DAGGER,	// 31
	APPLY_RESIST_BELL,		// 32
	APPLY_RESIST_FAN,		// 33
	APPLY_RESIST_BOW,		// 34
	APPLY_RESIST_FIRE,		// 35
	APPLY_RESIST_ELEC,		// 36
	APPLY_RESIST_MAGIC,		// 37
	APPLY_RESIST_WIND,		// 38
	APPLY_REFLECT_MELEE,	// 39
	APPLY_REFLECT_CURSE,	// 40
	APPLY_POISON_REDUCE,	// 41
	APPLY_KILL_SP_RECOVER,	// 42
	APPLY_EXP_DOUBLE_BONUS,	// 43
	APPLY_GOLD_DOUBLE_BONUS,// 44
	APPLY_ITEM_DROP_BONUS,	// 45
	APPLY_POTION_BONUS,		// 46
	APPLY_KILL_HP_RECOVER,	// 47
	APPLY_IMMUNE_STUN,		// 48
	APPLY_IMMUNE_SLOW,		// 49
	APPLY_IMMUNE_FALL,		// 50
	APPLY_SKILL,			// 51
	APPLY_BOW_DISTANCE,		// 52
	APPLY_ATT_GRADE_BONUS,	// 53
	APPLY_DEF_GRADE_BONUS,	// 54
	APPLY_MAGIC_ATT_GRADE,	// 55
	APPLY_MAGIC_DEF_GRADE,	// 56
	APPLY_CURSE_PCT,		// 57
	APPLY_MAX_STAMINA,		// 58
	APPLY_ATTBONUS_WARRIOR,	// 59
	APPLY_ATTBONUS_ASSASSIN,// 60
	APPLY_ATTBONUS_SURA,	// 61
	APPLY_ATTBONUS_SHAMAN,	// 62
	APPLY_ATTBONUS_MONSTER,	// 63
	APPLY_MALL_ATTBONUS,			// 64
	APPLY_MALL_DEFBONUS,			// 65
	APPLY_MALL_EXPBONUS,			// 66
	APPLY_MALL_ITEMBONUS,			// 67
	APPLY_MALL_GOLDBONUS,			// 68
	APPLY_MAX_HP_PCT,				// 69
	APPLY_MAX_SP_PCT,				// 70
	APPLY_SKILL_DAMAGE_BONUS,		// 71
	APPLY_NORMAL_HIT_DAMAGE_BONUS,	// 72
	APPLY_SKILL_DEFEND_BONUS,		// 73
	APPLY_NORMAL_HIT_DEFEND_BONUS,	// 74

	APPLY_EXTRACT_HP_PCT,			// 75

	APPLY_RESIST_WARRIOR,			// 76
	APPLY_RESIST_ASSASSIN,			// 77
	APPLY_RESIST_SURA,				// 78
	APPLY_RESIST_SHAMAN,			// 79
	APPLY_ENERGY,					// 80
	APPLY_DEF_GRADE,				// 81
	APPLY_COSTUME_ATTR_BONUS,		// 84
	APPLY_MAGIC_ATTBONUS_PER,		// 85
	APPLY_MELEE_MAGIC_ATTBONUS_PER,	// 86	

	APPLY_RESIST_ICE,		// 87
	APPLY_RESIST_EARTH,		// 88
	APPLY_RESIST_DARK,		// 89

	APPLY_ANTI_CRITICAL_PCT,	//90
	APPLY_ANTI_PENETRATE_PCT,	//91
	APPLY_ATTBONUS_BOSS, //92
	APPLY_ATTBONUS_METIN, //93
	
	APPLY_ENCHANT_ELECT,
	APPLY_ENCHANT_FIRE,
	APPLY_ENCHANT_ICE,
	APPLY_ENCHANT_WIND,
	APPLY_ENCHANT_EARTH,
	APPLY_ENCHANT_DARK,

#if defined(__CONQUEROR_LEVEL__)
	APPLY_SUNGMA_STR,					// 100
	APPLY_SUNGMA_HP,					// 101
	APPLY_SUNGMA_MOVE,					// 102
	APPLY_SUNGMA_IMMUNE,				// 103
#endif

#ifdef BONUS_PCT
	APPLY_ATTBONUS_ANIMAL_PCT,
	APPLY_ATTBONUS_UNDEAD_PCT,
	APPLY_ATTBONUS_DEVIL_PCT,
	APPLY_ATTBONUS_ORC_PCT,
	APPLY_ATTBONUS_MILGYO_PCT,
	APPLY_ATTBONUS_DESERT_PCT,
	APPLY_ATTBONUS_INSECT_PCT,
	APPLY_ATTBONUS_TREE_PCT,
	APPLY_ATTBONUS_BOSS_PCT,
	APPLY_ATTBONUS_METIN_PCT,
	APPLY_ATTBONUS_CZ_PCT,
	APPLY_ATTBONUS_HUMAN_PCT,
	APPLY_ATTBONUS_MONSTER_PCT,
	APPLY_ENCHANT_ELECT_PCT,
	APPLY_ENCHANT_FIRE_PCT,
	APPLY_ENCHANT_ICE_PCT,
	APPLY_ENCHANT_WIND_PCT,
	APPLY_ENCHANT_EARTH_PCT,
	APPLY_ENCHANT_DARK_PCT,
	APPLY_RESIST_ELECT_PCT,
	APPLY_RESIST_FIRE_PCT,
	APPLY_RESIST_ICE_PCT,
	APPLY_RESIST_WIND_PCT,
	APPLY_RESIST_EARTH_PCT,
	APPLY_RESIST_DARK_PCT,
	APPLY_RESIST_HUMAN_PCT,
	APPLY_RESIST_FALL,
	APPLY_RESIST_COMBAT,
#endif

	MAX_APPLY_NUM,
};

enum EOnClickEvents
{
	ON_CLICK_NONE,
	ON_CLICK_SHOP,
	ON_CLICK_TALK,
	ON_CLICK_MAX_NUM
};

enum EOnIdleEvents
{
	ON_IDLE_NONE,
	ON_IDLE_GENERAL,
	ON_IDLE_MAX_NUM
};

enum EWindows
{
	RESERVED_WINDOW,
	INVENTORY,
	EQUIPMENT,
	SAFEBOX,
	MALL,
	DRAGON_SOUL_INVENTORY,
#if defined(__ATTR_6TH_7TH__)
	ATTR67_ADD,
#endif
#ifdef __AURA_SYSTEM__
	AURA_REFINE,
#endif
#ifdef ENABLE_SWITCHBOT
	SWITCHBOT,
#endif
	BELT_INVENTORY,
	GROUND
};

enum EMobSizes
{
	MOBSIZE_RESERVED,
	MOBSIZE_SMALL,
	MOBSIZE_MEDIUM,
	MOBSIZE_BIG
};

enum EAIFlags
{
	AIFLAG_AGGRESSIVE	= (1 << 0),
	AIFLAG_NOMOVE	= (1 << 1),
	AIFLAG_COWARD	= (1 << 2),
	AIFLAG_NOATTACKSHINSU	= (1 << 3),
	AIFLAG_NOATTACKJINNO	= (1 << 4),
	AIFLAG_NOATTACKCHUNJO	= (1 << 5),
	AIFLAG_ATTACKMOB = (1 << 6 ),
	AIFLAG_BERSERK	= (1 << 7),
	AIFLAG_STONESKIN	= (1 << 8),
	AIFLAG_GODSPEED	= (1 << 9),
	AIFLAG_DEATHBLOW	= (1 << 10),
	AIFLAG_REVIVE		= (1 << 11),
};

enum EMobStatType
{
	MOB_STATTYPE_POWER,
	MOB_STATTYPE_TANKER,
	MOB_STATTYPE_SUPER_POWER,
	MOB_STATTYPE_SUPER_TANKER,
	MOB_STATTYPE_RANGE,
	MOB_STATTYPE_MAGIC,
	MOB_STATTYPE_MAX_NUM
};

enum EImmuneFlags
{
	IMMUNE_STUN		= (1 << 0),
	IMMUNE_SLOW		= (1 << 1),
	IMMUNE_FALL		= (1 << 2),
	IMMUNE_CURSE	= (1 << 3),
	IMMUNE_POISON	= (1 << 4),
	IMMUNE_TERROR	= (1 << 5),
	IMMUNE_REFLECT	= (1 << 6),
};

enum EMobEnchants
{
	MOB_ENCHANT_CURSE,
	MOB_ENCHANT_SLOW,
	MOB_ENCHANT_POISON,
	MOB_ENCHANT_STUN,
	MOB_ENCHANT_CRITICAL,
	MOB_ENCHANT_PENETRATE,
	MOB_ENCHANTS_MAX_NUM
};

enum EMobResists
{
	MOB_RESIST_SWORD,
	MOB_RESIST_TWOHAND,
	MOB_RESIST_DAGGER,
	MOB_RESIST_BELL,
	MOB_RESIST_FAN,
	MOB_RESIST_BOW,
	MOB_RESIST_FIRE,
	MOB_RESIST_ELECT,
	MOB_RESIST_MAGIC,
	MOB_RESIST_WIND,
	MOB_RESIST_POISON,
	MOB_RESISTS_MAX_NUM
};

enum
{
	SKILL_ATTR_TYPE_NORMAL = 1,
	SKILL_ATTR_TYPE_MELEE,
	SKILL_ATTR_TYPE_RANGE,
	SKILL_ATTR_TYPE_MAGIC
};

enum
{
	SKILL_NORMAL,
	SKILL_MASTER,
	SKILL_GRAND_MASTER,
	SKILL_PERFECT_MASTER,
};

enum EGuildWarType
{
	GUILD_WAR_TYPE_FIELD,
	GUILD_WAR_TYPE_BATTLE,
	GUILD_WAR_TYPE_FLAG,
	GUILD_WAR_TYPE_MAX_NUM
};
enum EGuildWarState
{
	GUILD_WAR_NONE,
	GUILD_WAR_SEND_DECLARE,
	GUILD_WAR_REFUSE,
	GUILD_WAR_RECV_DECLARE,
	GUILD_WAR_WAIT_START,
	GUILD_WAR_CANCEL,
	GUILD_WAR_ON_WAR,
	GUILD_WAR_END,
	GUILD_WAR_OVER,
	GUILD_WAR_RESERVE,

	GUILD_WAR_DURATION = 30*60, // 1�ð�
	GUILD_WAR_WIN_POINT = 1000,
	GUILD_WAR_LADDER_HALF_PENALTY_TIME = 12*60*60,
};

enum EAttributeSet
{
	ATTRIBUTE_SET_WEAPON,
	ATTRIBUTE_SET_BODY,
	ATTRIBUTE_SET_WRIST,
	ATTRIBUTE_SET_FOOTS,
	ATTRIBUTE_SET_NECK,
	ATTRIBUTE_SET_HEAD,
	ATTRIBUTE_SET_SHIELD,
	ATTRIBUTE_SET_EAR,
	ATTRIBUTE_SET_TALISMAN,
#if defined(ENABLE_GLOVE_SYSTEM) && defined(ENABLE_GLOVE_ITEM_ATTR)
	ATTRIBUTE_SET_GLOVE,
#endif
	ATTRIBUTE_SET_MAX_NUM
};

enum EPrivType
{
	PRIV_NONE,
	PRIV_ITEM_DROP,
	PRIV_GOLD_DROP,
	PRIV_GOLD10_DROP,
	PRIV_EXP_PCT,
	MAX_PRIV_NUM,
};

enum EMoneyLogType
{
	MONEY_LOG_RESERVED,
	MONEY_LOG_MONSTER,
	MONEY_LOG_SHOP,
	MONEY_LOG_REFINE,
	MONEY_LOG_QUEST,
	MONEY_LOG_GUILD,
	MONEY_LOG_MISC,
	MONEY_LOG_MONSTER_KILL,
	MONEY_LOG_DROP,
	MONEY_LOG_TYPE_MAX_NUM,
};

enum EPremiumTypes
{
	PREMIUM_EXP,
	PREMIUM_ITEM,
	PREMIUM_SAFEBOX,
	PREMIUM_AUTOLOOT,
	PREMIUM_FISH_MIND,
	PREMIUM_MARRIAGE_FAST,
	PREMIUM_GOLD,
#ifdef __PREMIUM_PRIVATE_SHOP__
	PREMIUM_PRIVATE_SHOP,
#endif
	PREMIUM_MAX_NUM = 9
};

enum SPECIAL_EFFECT
{
	SE_NONE,

	SE_HPUP_RED,
	SE_SPUP_BLUE,
	SE_SPEEDUP_GREEN,
	SE_DXUP_PURPLE,
	SE_CRITICAL,
	SE_PENETRATE,
	SE_BLOCK,
	SE_DODGE,
	SE_CHINA_FIREWORK,
	SE_SPIN_TOP,
	SE_SUCCESS,
	SE_FAIL,
	SE_FR_SUCCESS,
	SE_LEVELUP_ON_14_FOR_GERMANY,
	SE_LEVELUP_UNDER_15_FOR_GERMANY,
	SE_PERCENT_DAMAGE1,
	SE_PERCENT_DAMAGE2,
	SE_PERCENT_DAMAGE3,

	SE_AUTO_HPUP,
	SE_AUTO_SPUP,

	SE_EQUIP_RAMADAN_RING,		
	SE_EQUIP_HALLOWEEN_CANDY,	
	SE_EQUIP_HAPPINESS_RING,	
	SE_EQUIP_LOVE_PENDANT,		
#ifdef __SASH_SYSTEM__
	SE_EFFECT_SASH_SUCCEDED,
	SE_EFFECT_SASH_EQUIP,
#endif
#ifdef __VERSION_162__
	SE_EFFECT_HEALER,
#endif
};

#include "item_length.h"

// inventory�� position�� ��Ÿ���� ����ü
// int���� �Ͻ��� ����ȯ�� �ִ� ������,
// �κ� ���õ� ��� �Լ��� window_type�� ���� �ʰ�, cell �ϳ��� �޾ұ� ������,(�������� �κ��� �ϳ� ���̾ inventory type�̶��� �ʿ������ ������,)
// �κ� ���� ��� �Լ� ȣ��κ��� �����ϴ� ���� �����ϱ� �����̴�.

#ifdef __HIDE_COSTUME_SYSTEM__
enum ECostumeOptionFlags
{
	COSTUME_FLAG_HEAD = (1 << 0),
	COSTUME_FLAG_BODY = (1 << 1),
#ifdef ENABLE_WEAPON_COSTUME_SYSTEM
	COSTUME_FLAG_WEAPON = (1 << 2),
#endif

#ifdef __SASH_SYSTEM__
	COSTUME_FLAG_SASH = (1 << 3),
#endif

};
#endif

enum EDragonSoulRefineWindowSize
{
	DRAGON_SOUL_REFINE_GRID_MAX = 15,
};

enum EMisc2
{
	DRAGON_SOUL_EQUIP_SLOT_START = INVENTORY_MAX_NUM + WEAR_MAX_NUM, // 180 + 32 ( 212 )
	DRAGON_SOUL_EQUIP_SLOT_END = DRAGON_SOUL_EQUIP_SLOT_START + (DS_SLOT_MAX * DRAGON_SOUL_DECK_MAX_NUM), // 212 + 12 ( 224 )
	DRAGON_SOUL_EQUIP_RESERVED_SLOT_END = DRAGON_SOUL_EQUIP_SLOT_END + (DS_SLOT_MAX * DRAGON_SOUL_DECK_RESERVED_MAX_NUM), // 224 + 18 ( 242 )

	BELT_INVENTORY_SLOT_START = DRAGON_SOUL_EQUIP_RESERVED_SLOT_END, // 242
	BELT_INVENTORY_SLOT_END = BELT_INVENTORY_SLOT_START + BELT_INVENTORY_SLOT_COUNT, // 242 + 16 ( 258 )

#ifdef ENABLE_CUSTOM_INVENTORY
	CUSTOM_INVENTORY_SLOT_START = BELT_INVENTORY_SLOT_END,
	CUSTOM_INVENTORY_SLOT_END = CUSTOM_INVENTORY_SLOT_START + (CUSTOM_INVENTORY_MAX_NUM * CUSTOM_INVENTORY_CATEGORY_NUM),
	INVENTORY_AND_EQUIP_SLOT_MAX = CUSTOM_INVENTORY_SLOT_END,
#else
	INVENTORY_AND_EQUIP_SLOT_MAX = BELT_INVENTORY_SLOT_END,
#endif
};

#ifdef ENABLE_SWITCHBOT

enum SwitchbotValues
{
	SWITCHBOT_SLOT_COUNT = 5,
	SWITCHBOT_ALTERNATIVE_COUNT = 2,
	//1 = Switching Item
	//2 = Yang
	SWITCHBOT_PRICE_TYPE = 1,
	//Amount Swtichting Items the Yang-Price
	SWITCHBOT_PRICE_AMOUNT = 1,
};

const DWORD c_arSwitchingItems[3] =
{
	39028,
	71084,
	76014,
};
#endif



#pragma pack(push, 1)
typedef struct SItemPos
{
	BYTE window_type;
	WORD cell;
    SItemPos ()
    {
        window_type = INVENTORY;
		cell = WORD_MAX;
    }

	SItemPos (BYTE _window_type, WORD _cell)
    {
        window_type = _window_type;
        cell = _cell;
    }

	bool IsValidItemPosition() const
	{
		switch (window_type)
		{
		case RESERVED_WINDOW:
			return false;
		case INVENTORY:
		case EQUIPMENT:
		case BELT_INVENTORY:
			return cell < INVENTORY_AND_EQUIP_SLOT_MAX;
		case DRAGON_SOUL_INVENTORY:
			return cell < (DRAGON_SOUL_INVENTORY_MAX_NUM);
		case SAFEBOX:
		case MALL:
			return false;
#if defined(__ATTR_6TH_7TH__)
		case ATTR67_ADD:
			return cell < ATTR67_ADD_SLOT_MAX;
#endif
#ifdef ENABLE_SWITCHBOT
		case SWITCHBOT:
			return cell < SWITCHBOT_SLOT_COUNT;
#endif
		default:
			return false;
		}
		return false;
	}

	bool IsEquipPosition() const
	{
		return ((INVENTORY == window_type || EQUIPMENT == window_type) && cell >= INVENTORY_MAX_NUM && cell < INVENTORY_MAX_NUM + WEAR_MAX_NUM)
			|| IsDragonSoulEquipPosition();
	}

	bool IsDragonSoulEquipPosition() const
	{
		return (DRAGON_SOUL_EQUIP_SLOT_START <= cell) && (DRAGON_SOUL_EQUIP_SLOT_END > cell);
	}

	bool IsBeltInventoryPosition() const
	{
		return (BELT_INVENTORY_SLOT_START <= cell) && (BELT_INVENTORY_SLOT_END > cell);
	}

	bool IsDefaultInventoryPosition() const
	{
		return INVENTORY == window_type && cell < INVENTORY_MAX_NUM;
	}
#ifdef ENABLE_SWITCHBOT
	bool IsSwitchbotPosition() const
	{
		return SWITCHBOT == window_type && cell < SWITCHBOT_SLOT_COUNT;
	}
#endif
#ifdef ENABLE_CUSTOM_INVENTORY
	bool IsCustomInventoryPosition() const
	{
		return ((INVENTORY == window_type) && cell >= CUSTOM_INVENTORY_SLOT_START && cell < CUSTOM_INVENTORY_SLOT_END);
	}

	int GetCustomInventoryCategory() const
	{
		for(BYTE catIndex = 0; catIndex < CUSTOM_INVENTORY_CATEGORY_NUM; catIndex++)
		{
			if(cell >= (CUSTOM_INVENTORY_SLOT_START + catIndex * CUSTOM_INVENTORY_MAX_NUM) && cell < (CUSTOM_INVENTORY_SLOT_START + (catIndex + 1) * CUSTOM_INVENTORY_MAX_NUM))
				return catIndex;
		}
		
		return -1;
	} 
#endif
	bool operator==(const struct SItemPos& rhs) const
	{
		return (window_type == rhs.window_type) && (cell == rhs.cell);
	}
	bool operator<(const struct SItemPos& rhs) const
	{
		return (window_type < rhs.window_type) || ((window_type == rhs.window_type) && (cell < rhs.cell));
	}
	bool operator!=(const struct SItemPos& rhs) const
	{
		return (window_type != rhs.window_type) || (cell != rhs.cell);
	}
} TItemPos;

const TItemPos NPOS (RESERVED_WINDOW, WORD_MAX);

typedef enum
{
	SHOP_COIN_TYPE_GOLD, // DEFAULT VALUE
	SHOP_COIN_TYPE_SECONDARY_COIN,
} EShopCoinType;
enum EAlignmentBonus
{
	NAME_ALIGNMENT_1 = 10000,
	NAME_ALIGNMENT_2 = 40000,
	NAME_ALIGNMENT_3 = 80000,
	NAME_ALIGNMENT_4 = 120000,

	ALIGNMENT_TIME = 60*60*24*365,
};
#ifdef __AURA_SYSTEM__
typedef struct SAuraRefineInfo
{
	BYTE bAuraRefineInfoLevel;
	BYTE bAuraRefineInfoExpPercent;
} TAuraRefineInfo;

enum EAuraMisc
{
	AURA_MAX_LEVEL = 250,
	AURA_REFINE_MAX_DISTANCE = 1000,
};

enum EAuraWindowType
{
	AURA_WINDOW_TYPE_ABSORB,
	AURA_WINDOW_TYPE_GROWTH,
	AURA_WINDOW_TYPE_EVOLVE,
	AURA_WINDOW_TYPE_MAX,
};

enum EAuraSlotType
{
	AURA_SLOT_MAIN,
	AURA_SLOT_SUB,
	AURA_SLOT_RESULT,
	AURA_SLOT_MAX
};

enum EAuraGradeType
{
	AURA_GRADE_NONE,
	AURA_GRADE_ORDINARY,
	AURA_GRADE_SIMPLE,
	AURA_GRADE_NOBLE,
	AURA_GRADE_SPARKLING,
	AURA_GRADE_MAGNIFICENT,
	AURA_GRADE_RADIANT,
	AURA_GRADE_MAX_NUM,
};
enum EAuraRefineInfoType
{
	AURA_REFINE_INFO_STEP,
	AURA_REFINE_INFO_LEVEL_MIN,
	AURA_REFINE_INFO_LEVEL_MAX,
	AURA_REFINE_INFO_NEED_EXP,
	AURA_REFINE_INFO_MATERIAL_VNUM,
	AURA_REFINE_INFO_MATERIAL_COUNT,
	AURA_REFINE_INFO_NEED_GOLD,
	AURA_REFINE_INFO_EVOLVE_PCT,
	AURA_REFINE_INFO_MAX
};

enum ERefineInfoType
{
	AURA_REFINE_INFO_SLOT_CURRENT,
	AURA_REFINE_INFO_SLOT_NEXT,
	AURA_REFINE_INFO_SLOT_EVOLVED,
	AURA_REFINE_INFO_SLOT_MAX
};
#endif

#ifdef ENABLE_REFINE_ELEMENT
enum ERefineElementType
{
	REFINE_ELEMENT_CATEGORY_NONE,
	REFINE_ELEMENT_CATEGORY_ELECT,
	REFINE_ELEMENT_CATEGORY_FIRE,
	REFINE_ELEMENT_CATEGORY_ICE,
	REFINE_ELEMENT_CATEGORY_WIND,
	REFINE_ELEMENT_CATEGORY_EARTH,
	REFINE_ELEMENT_CATEGORY_DARK,
	REFINE_ELEMENT_CATEGORY_MAX,
};

enum ERefineElement
{
	REFINE_ELEMENT_MAX = 3,
	ELEMENT_MIN_REFINE_LEVEL = 7,
	REFINE_ELEMENT_UPGRADE_YANG = 3000000,
	REFINE_ELEMENT_DOWNGRADE_YANG = 10000000,
	REFINE_ELEMENT_CHANGE_YANG = 10000000,
	
	REFINE_ELEMENT_UPGRADE_PROBABILITY = 100,
	REFINE_ELEMENT_DOWNGRADE_PROBABILITY = 100,
	REFINE_ELEMENT_CHANGE_PROBABILITY = 100,
	
	REFINE_ELEMENT_TYPE_UPGRADE = 0,
	REFINE_ELEMENT_TYPE_DOWNGRADE = 1,
	REFINE_ELEMENT_TYPE_CHANGE = 2,
	REFINE_ELEMENT_TYPE_UPGRADE_SUCCES = 10,
	REFINE_ELEMENT_TYPE_UPGRADE_FAIL = 11,
	REFINE_ELEMENT_TYPE_DOWNGRADE_SUCCES = 12,
	REFINE_ELEMENT_TYPE_CHANGE_SUCCES = 13,

	REFINE_ELEMENT_RANDOM_VALUE_MIN = 1,
	REFINE_ELEMENT_RANDOM_VALUE_MAX = 8,
	REFINE_ELEMENT_RANDOM_BONUS_VALUE_MIN = 2,
	REFINE_ELEMENT_RANDOM_BONUS_VALUE_MAX = 12,
};
#endif

#if defined(__DAILY_GIFT_SYSTEM__)
enum EDailyGift
{
	DAILY_GIFT_CLOSE = 0,
	DAILY_GIFT_OPEN = 1,
	DAILY_GIFT_COLLECT = 2,
	DAILY_GIFT_COLLECT_USE_TICKET = 3,

	DAILY_GIFT_COLLECT_LOCK = 0,
	DAILY_GIFT_COLLECT_WAIT = 1,
	DAILY_GIFT_COLLECT_SUCCESS = 2,

	DAILY_GIFT_DAY = 1,
	DAILY_GIFT_WEEK_DAYS = 7,
	DAILY_GIFT_TICKET_ITEM = 72319,
};
#endif
#ifdef __MULTI_LANGUAGE_SYSTEM__
enum EMultiLocale
{
	MAX_QUEST_NOTICE_ARGS = 5
};

enum ELocale
{
	LOCALE_YMIR, // Korea
	LOCALE_EN, // United Kingdom
	LOCALE_PT, // Portugal
	LOCALE_ES, // Spain
	LOCALE_FR, // France
	LOCALE_DE, // Germany
	LOCALE_RO, // Romania
	LOCALE_PL, // Poland
	LOCALE_IT, // Italy
	LOCALE_CZ, // Czech
	LOCALE_HU, // Hungary
	LOCALE_TR, // Turkey
	LOCALE_MAX_NUM,
	LOCALE_DEFAULT = LOCALE_EN,
};
#endif


#ifdef __STAGE_EVENT__
enum EStageEvent
{
	STAGE_COUNT = 4,

	STAGE_TYPE_SOLO = 0,
	STAGE_TYPE_EMPIRE,
	STAGE_TYPE_HWID,
	STAGE_TYPE_IP,
	STAGE_TYPE_GUILD,
	STAGE_TYPE_MAX,

	STAGE_MISSION_MOB = 0,
	STAGE_MISSION_BUY,
	STAGE_MISSION_EARN,
	STAGE_MISSION_GIVING,
	STAGE_MISSION_EXP,
	STAGE_MISSION_MAX,

	STAGE_REWARD_YANG = 0,
	STAGE_REWARD_BONUS,
	STAGE_REWARD_ITEM,
	STAGE_REWARD_TAXES,
	STAGE_REWARD_MAX,
};
#endif

#ifdef ENABLE_REWARD_SYSTEM
enum
{
	REWARD_MISSION_LEVEL_UP,
	REWARD_MISSION_LEVEL_UP_PET,
	REWARD_MISSION_SKILL_UPGRADE,
	REWARD_MISSION_KILL_MONSTER,
	REWARD_MISSION_KILL_STONE,
	REWARD_MISSION_KILL_BOSS,
	REWARD_MISSION_INVENTORY_SLOT,
	REWARD_MISSION_OFFLINESHOP_SLOT,
	REWARD_MISSION_AVERAGE_BONUS,
	REWARD_MISSION_BATTLEPASS,
	REWARD_MISSION_FIRST_ITEM,
	REWARD_MISSION_CUSTOM_SASH,
	REWARD_MISSION_BIOLOG,
	REWARD_MISSION_PASSIVE_SKILL_COMPLETE,
	REWARD_MISSION_DUNGEON,
	REWARD_MISSION_USE_ITEM,
	REWARD_MISSION_SELL_ITEM,
	REWARD_MISSION_BUY_ITEM,
	REWARD_MISSION_PLAYTIME,
	REWARD_MISSION_COMPLETE_SKILL,
};
#endif


#pragma pack(pop)

#endif
