"""Generate the source-derived tables of the Parity inventory.

Run from anywhere: `python3 .scratch/parity/tools/gen.py`. It rewrites the generated files in
`.scratch/parity/` and keeps the hand-maintained columns (status, scenario, note) of every row whose
ID already exists, so a status set by hand survives a regeneration. A row whose ID disappears from
the source is reported and dropped; a new ID starts as `missing`.

Only code the legacy build compiles is listed (see `active.py`).
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
from active import LEGACY, active_lines, read  # noqa: E402

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..'))
REPO = os.path.normpath(os.path.join(ROOT, '../..'))
GAME = os.path.join(LEGACY, 'game')
QUESTS = os.path.join(REPO, 'legacy/gamedata/locale/europe/quest')

HEADER = ('| id | source | what | status | scenario | note |\n'
          '|---|---|---|---|---|---|\n')
ROW = re.compile(r'^\|\s*`([^`]+)`\s*\|(.*)\|\s*$')


def existing(path):
    """Hand-maintained columns by ID from a previous run."""
    kept = {}
    if not os.path.exists(path):
        return kept
    for line in read(path):
        match = ROW.match(line)
        if not match:
            continue
        cells = [cell.strip() for cell in match.group(2).split('|')]
        if len(cells) >= 5:
            kept[match.group(1)] = cells[2:5]
    return kept


def write(name, title, intro, rows, default_status='missing'):
    """Write one inventory file. `rows` is [(id, source, what, status_hint, note_hint)]."""
    path = os.path.join(ROOT, name)
    kept = existing(path)
    seen = set()
    lines = ['# ' + title, '', intro.strip(), '',
             'Generated by `tools/gen.py` from the live legacy source; edit only the status, '
             'scenario, and note columns.', '', HEADER.rstrip('\n')]
    counts = {}
    for ident, source, what, status_hint, note_hint in rows:
        if ident in seen:
            raise SystemExit('duplicate id %s in %s' % (ident, name))
        seen.add(ident)
        status, scenario, note = kept.get(ident, [status_hint or default_status, '', note_hint])
        counts[status] = counts.get(status, 0) + 1
        lines.append('| `%s` | %s | %s | %s | %s | %s |' % (ident, source, what, status, scenario,
                                                          note))
    for gone in sorted(set(kept) - seen):
        print('%s: %s is no longer in the source and was dropped' % (name, gone))
    lines.append('')
    with open(path, 'w', encoding='utf-8') as handle:
        handle.write('\n'.join(lines))
    print('%-22s %4d rows  %s' % (name, len(rows), counts))
    return len(rows)


def cite(path, number):
    return '`%s:%d`' % (os.path.relpath(path, LEGACY), number)


def function_body(lines, start):
    """The (first, last) 0-based line indices of the brace block that starts at or after `start`."""
    depth = 0
    opened = False
    for index in range(start, len(lines)):
        code = re.sub(r'//.*', '', lines[index])
        code = re.sub(r'"(\\.|[^"\\])*"', '""', code)
        for char in code:
            if char == '{':
                depth += 1
                opened = True
            elif char == '}':
                depth -= 1
                if opened and depth == 0:
                    return start, index
    raise SystemExit('unbalanced braces from line %d' % (start + 1))


# --- client packets ------------------------------------------------------------------------------

def cg_bytes():
    source = read(os.path.join(REPO, 'protocol/src/cg_inventory.rs'))
    values = {}
    for line in source:
        match = re.match(r'pub const (\w+): CgHeader = CgHeader\((0x[0-9a-f]+)\);', line)
        if match:
            values[match.group(1)] = int(match.group(2), 16)
    return values


ANALYZERS = [
    ('input.cpp', 'CInputHandshake', 'handshake'),
    ('input_auth.cpp', 'CInputAuth', 'auth'),
    ('input_login.cpp', 'CInputLogin', 'login'),
    ('input_main.cpp', 'CInputMain', 'game'),
    ('input_main.cpp', 'CInputDead', 'dead'),
]
NOT_HANDLERS = {'if', 'for', 'while', 'switch', 'return', 'sizeof', 'sys_log', 'sys_err',
                'reinterpret_cast', 'static_cast', 'GetCharacter', 'IsObserverMode', 'instance'}


def handler_name(lines, first, last):
    """The first free function the arm starting after line `first` calls, or '' for none.

    The scan stops at the arm's `break`/`return` or at the next `else if`, skips further `case`
    labels (a fall-through shares the next arm's body) and preprocessor lines, and prefers a call
    that is not a member access (`d->SetPhase`) over one that is.
    """
    member = ''
    for index in range(first, last + 1):
        text = re.sub(r'//.*', '', lines[index]).strip()
        if text.startswith('#') or re.match(r'case\s+\w+\s*:$', text):
            continue
        if re.match(r'(break|return)\b', text) or re.match(r'\}?\s*else\s+if\b', text) \
                or text.startswith('default:'):
            break
        for match in re.finditer(r'(->|\.|::)?\s*([A-Za-z_]\w*)\s*\(', text):
            name = match.group(2)
            if name in NOT_HANDLERS or name.startswith(('HEADER_', 'TPacket')):
                continue
            if match.group(1):
                member = member or name
                continue
            return name
    return member


# Arms whose effect a function name does not describe.
WHAT = {
    'cg.handshake.state_checker': 'asks the DB for the Channel status list '
                                  '(`HEADER_GD_REQUEST_CHANNELSTATUS`), once per descriptor',
    'cg.handshake.mark_login': 'switches to the login phase on a mark server, else closes',
}


def client_packets():
    values = cg_bytes()
    path = os.path.join(GAME, 'input.cpp')
    lines = read(path)
    keep = next(i for i, line in enumerate(lines) if re.search(r'if \(bHeader == 0\)', line))
    unknown = next(i for i, line in enumerate(lines) if 'UNKNOWN HEADER' in line)
    extra = next(i for i, line in enumerate(lines) if 'iExtraPacketSize' in line)
    negative = next(i for i, line in enumerate(lines)
                    if re.search(r'if \(iExtraPacketSize < 0\)', line))
    # `CInputProcessor::Process` handles these before any phase analyzer sees the frame.
    rows = [('cg.any.keep_alive', cite(path, keep + 1),
             'header 0x00 in every phase → one byte consumed, no analyzer call', 'missing', ''),
            ('cg.any.unknown_header', cite(path, unknown + 1),
             'a header the phase table does not register → descriptor closed', 'missing', ''),
            ('cg.any.variable_length', cite(path, extra + 1),
             'a registered header whose analyzer returns a size adds it to the phase-table '
             'length, so the frame is as long as the record says it is', 'missing', ''),
            ('cg.any.analyzer_refusal', cite(path, negative + 1),
             'an analyzer that returns -1 consumes nothing and leaves the descriptor open',
             'missing', '')]
    for file_name, klass, phase in ANALYZERS:
        path = os.path.join(GAME, file_name)
        lines = read(path)
        live = active_lines(path)
        start = next(i for i, line in enumerate(lines)
                     if re.match(r'\s*int\s+%s::Analyze\s*\(' % klass, line))
        first, last = function_body(lines, start)
        arms = []
        for index in range(first, last + 1):
            if index + 1 not in live:
                continue
            # Match every CG header name, not only the `HEADER_CG_` prefix: `ENVANTER_BLACK`
            # (0xe2) is a client header without it.
            for name in re.findall(r'(?:case\s+|bHeader\s*==\s*)(\w+)', lines[index]):
                if name in values:
                    arms.append((index, name))
        for position, (index, name) in enumerate(arms):
            end = arms[position + 1][0] - 1 if position + 1 < len(arms) else last
            handler = handler_name(lines, index + 1, last)
            byte = values.get(name)
            ident = 'cg.%s.%s' % (phase, name.removeprefix('HEADER_CG_').lower())
            effect = WHAT.get(ident) or ('`%s`' % handler if handler else 'consumed, no effect')
            what = '%s (%s) → %s' % (name, '0x%02x' % byte if byte is not None else '?', effect)
            rows.append((ident, cite(path, index + 1), what, 'missing', ''))
    return rows


# --- sub-headers ---------------------------------------------------------------------------------

# Handlers whose `case` labels are not client sub-commands: `Attack` switches on skill numbers,
# which belong to the skill rules, and `QuickslotAdd` on an item-use constant.
NOT_SUB_DISPATCH = {'Analyze', 'Attack', 'QuickslotAdd'}


def sub_headers():
    rows = []
    for file_name, klass in (('input_login.cpp', 'CInputLogin'), ('input_main.cpp', 'CInputMain')):
        path = os.path.join(GAME, file_name)
        lines = read(path)
        live = active_lines(path)
        for index, line in enumerate(lines):
            match = re.match(r'^(?:int|void|bool|size_t)\s+%s::(\w+)\s*\(' % klass, line)
            if not match or index + 1 not in live:
                continue
            handler = match.group(1)
            first, last = function_body(lines, index)
            for number in range(first, last + 1):
                if number + 1 not in live:
                    continue
                for label in re.findall(r'case\s+([A-Za-z_][\w:]*)\s*:', lines[number]):
                    # Analyze's own arms are packet headers (one, ENVANTER_BLACK, lacks the prefix);
                    # only the two nested switches are sub-commands.
                    if handler == 'Analyze' and not label.startswith(
                            ('DS_SUB_HEADER_', 'SUBHEADER_CG_PRIVATE_SHOP_')):
                        continue
                    if handler in NOT_SUB_DISPATCH and handler != 'Analyze':
                        continue
                    owner = handler
                    if handler == 'Analyze':
                        owner = 'PrivateShop' if 'PRIVATE_SHOP' in label else 'DragonSoulRefine'
                    rows.append(('sub.%s.%s' % (owner, label), cite(path, number + 1),
                                 '`%s::%s` arm `%s`' % (klass, handler, label), 'missing', ''))
    return rows


# --- server records ------------------------------------------------------------------------------

def server_records():
    path = os.path.join(REPO, 'protocol/src/gc_inventory.rs')
    source = '\n'.join(read(path))
    values = {m.group(1): int(m.group(2), 16) for m in
              re.finditer(r'pub const (HEADER_GC_\w+): GcHeader = GcHeader\((0x[0-9a-f]+)\);',
                          source)}
    rows = []
    for block in re.finditer(r'LegacyGcPacket \{(.*?)\n    \}', source, re.S):
        body = block.group(1)
        header = re.search(r'header: (HEADER_GC_\w+)', body)
        if not header:
            continue
        name = header.group(1)
        implemented = 'implemented_in_rust: true' in body
        struct = re.search(r'(?:server_struct|legacy_struct|cpp_type)\w*: (?:Some\()?"([^"]+)"',
                           body)
        what = '%s (0x%02x)%s' % (name, values[name], ', `%s`' % struct.group(1) if struct else '')
        rows.append(('gc.%s' % name[len('HEADER_GC_'):].lower(), '`protocol/src/gc_inventory.rs`',
                     what, 'codec' if implemented else 'missing', ''))
    return rows


# --- commands ------------------------------------------------------------------------------------

def commands():
    path = os.path.join(GAME, 'cmd.cpp')
    lines = read(path)
    live = active_lines(path)
    start = next(i for i, line in enumerate(lines) if 'struct command_info cmd_info[]' in line)
    first, last = function_body(lines, start)
    rows = []
    pattern = re.compile(r'\{\s*"([^"]*)",\s*(\w+),\s*(\w+),\s*(\w+),\s*(\w+)\s*\}')
    for index in range(first, last + 1):
        if index + 1 not in live:
            continue
        match = pattern.search(lines[index])
        if not match or match.group(1) in ('!RESERVED!', '\\n'):
            continue
        name, function, sub, position, level = match.groups()
        rows.append(('cmd.%s' % name, cite(path, index + 1),
                     '`%s` sub `%s`, %s, %s' % (function, sub, position, level), 'missing', ''))
    return rows


# --- quest API -----------------------------------------------------------------------------------

def quest_api():
    rows = []
    for file_name in sorted(os.listdir(GAME)):
        if not (file_name.startswith('questlua') and file_name.endswith('.cpp')):
            continue
        path = os.path.join(GAME, file_name)
        lines = read(path)
        live = active_lines(path)
        text = '\n'.join(lines)
        for match in re.finditer(r'luaL_reg\s+(\w+)\s*\[\s*\]\s*=', text):
            start = text.count('\n', 0, match.start())
            if start + 1 not in live:
                continue
            first, last = function_body(lines, start)
            variable = match.group(1)
            after = '\n'.join(lines[last:last + 200])
            table = re.search(r'(?:AddLuaFunctionTable|AppendLuaFunctionTable)\s*\(\s*"(\w+)"\s*,'
                              r'\s*%s\b' % variable, after)
            if variable == 'global_functions':
                prefix = ''
            elif table:
                prefix = table.group(1) + '.'
            else:
                raise SystemExit('no table for %s in %s' % (variable, file_name))
            for index in range(first, last + 1):
                if index + 1 not in live:
                    continue
                entry = re.search(r'\{\s*"(\w+)"\s*,\s*(\w+)\s*\}', lines[index])
                if entry:
                    rows.append(('lua.%s%s' % (prefix, entry.group(1)), cite(path, index + 1),
                                 '`%s`' % entry.group(2), 'missing', ''))
    return rows


# --- timed events --------------------------------------------------------------------------------

def timed_events():
    rows = []
    for file_name in sorted(os.listdir(GAME)):
        if not file_name.endswith('.cpp'):
            continue
        path = os.path.join(GAME, file_name)
        lines = read(path)
        live = active_lines(path)
        for index, line in enumerate(lines):
            match = re.match(r'\s*EVENTFUNC\s*\(\s*(\w+)\s*\)', line)
            if match and index + 1 in live:
                rows.append(('event.%s.%s' % (file_name[:-4], match.group(1)), cite(path, index + 1),
                             '`%s`' % match.group(1), 'missing', ''))
    return rows


# --- quest scripts -------------------------------------------------------------------------------

def quest_scripts():
    """Every quest script, then every Lua library the runtime loads before them."""
    rows = []
    for directory, folders, names in sorted(os.walk(QUESTS)):
        folders[:] = sorted(f for f in folders if f != 'object')
        for name in sorted(names):
            path = os.path.join(directory, name)
            relative = os.path.relpath(path, QUESTS)
            source = '`legacy/gamedata/locale/europe/quest/%s`' % relative
            stem = os.path.splitext(name)[0]
            if directory == QUESTS or relative.startswith('luaLibrary'):
                if name.endswith('.lua') or name == 'quest_functions':
                    rows.append(('questlib.%s' % stem, source, 'library', 'missing', ''))
                continue
            if name.endswith(('.quest', '.lua')):
                quests = re.findall(r'^\s*quest\s+(\w+)', '\n'.join(read(path)), re.M)
                what = 'quest %s' % ', '.join('`%s`' % q for q in quests) if quests else ''
                rows.append(('quest.%s' % stem, source, what, 'missing', ''))
    return rows


INTRO = {
    'client-packets.md': """
Every client-to-server header each legacy analyzer handles, one row per phase in which it is
handled. The handshake analyzer (`CInputHandshake`) also serves the Channel status query the
login screen sends. The handler named is the first call in the `case` arm; many handlers switch
again on a sub-header, and those sub-headers are listed in `sub-headers.md`. The `cg.any`
rows are the framing rules `CInputProcessor::Process` applies before any analyzer.
""",
    'sub-headers.md': """
Every sub-command a game-phase handler dispatches on (the `case` arms inside `CInputMain` and
`CInputLogin` handlers, and the two switches written inline in `CInputMain::Analyze`). Skill
numbers inside `Attack` are skill rules and are listed with the skills in `systems.md`.
""",
    'server-records.md': """
Every server-to-client record the Reference client decodes, from `protocol/src/gc_inventory.rs`.
A record is `codec` when the Rust codec exists and `ported` only when a scenario observes the
Rewrite sending it where legacy does.
""",
    'commands.md': """
Every chat command in `cmd_info` (`G/cmd.cpp`), with its minimum position and GM level. A
player command is reachable by every player; a GM command only through a GM grant.
""",
    'quest-api.md': """
Every Lua function the quest runtime registers (`G/questlua*.cpp`). A function is `ported` when a
scenario runs a quest that calls it and observes the legacy result.
""",
    'timed-events.md': """
Every timed event function (`EVENTFUNC`) in the live legacy game source. Each belongs to a system
and is ported with it; the row exists so that no timer is forgotten.
""",
    'quests.md': """
Every quest script in `legacy/gamedata/locale/europe/quest` (`quest.*`), and every Lua library the
quest runtime loads before them (`questlib.*`). All are live in the Rewrite (ADR-0004); `object/`
is legacy `qc` output and is not listed.
""",
}

if __name__ == '__main__':
    total = 0
    total += write('client-packets.md', 'Client packets', INTRO['client-packets.md'],
                   client_packets())
    total += write('sub-headers.md', 'Client sub-commands', INTRO['sub-headers.md'],
                   sub_headers())
    total += write('server-records.md', 'Server records', INTRO['server-records.md'],
                   server_records())
    total += write('commands.md', 'Chat commands', INTRO['commands.md'], commands())
    total += write('quest-api.md', 'Quest API', INTRO['quest-api.md'], quest_api())
    total += write('timed-events.md', 'Timed events', INTRO['timed-events.md'], timed_events())
    total += write('quests.md', 'Quest scripts', INTRO['quests.md'], quest_scripts())
    print('generated rows:', total)
