//! `cmd_info` (`G/cmd.cpp:262-564`): the commands `interpret_command` walks, in legacy's
//! order, under the owner's defines (`ENABLE_NEWSTUFF`, `__CASKET_PREVIEW_ENABLE__` and
//! `__WORLD_BOSS_EVENT__` on; `ENABLE_FULL_NOTICE`, `GIFT_SYSTEM`, `OFFLINE_SHOP` and
//! `ENABLE_SHOP_SEARCH` off).
//!
//! Entry 0, `!RESERVED!`, is never walked and the terminator is not an entry, so neither is
//! here. The subcommand column is left out: only the handlers this build ports read it, and
//! none of them does.

use super::{
    entry, CommandEntry, GM_GOD, GM_HIGH_WIZARD, GM_IMPLEMENTOR, GM_LOW_WIZARD, GM_PLAYER,
    GM_WIZARD, POS_DEAD, POS_FIGHTING, POS_FISHING, POS_MOUNTING,
};

/// The walked entries of `cmd_info`, in order.
pub(super) const COMMANDS: [CommandEntry; 267] = [
    entry("who", "do_who", POS_DEAD, GM_IMPLEMENTOR),
    entry("war", "do_war", POS_DEAD, GM_PLAYER),
    entry("warp", "do_warp", POS_DEAD, GM_LOW_WIZARD),
    entry("ds_change_attr", "do_ds_change_attr", POS_DEAD, GM_PLAYER),
    entry("user", "do_user", POS_DEAD, GM_HIGH_WIZARD),
    entry("notice", "do_notice", POS_DEAD, GM_HIGH_WIZARD),
    entry("notice_map", "do_map_notice", POS_DEAD, GM_LOW_WIZARD),
    entry("big_notice", "do_big_notice", POS_DEAD, GM_HIGH_WIZARD),
    entry("nowar", "do_nowar", POS_DEAD, GM_PLAYER),
    entry("purge", "do_purge", POS_DEAD, GM_WIZARD),
    entry("weaken", "do_weaken", POS_DEAD, GM_GOD),
    entry("dc", "do_disconnect", POS_DEAD, GM_LOW_WIZARD),
    entry("transfer", "do_transfer", POS_DEAD, GM_LOW_WIZARD),
    entry("goto", "do_goto", POS_DEAD, GM_LOW_WIZARD),
    entry("level", "do_level", POS_DEAD, GM_LOW_WIZARD),
    entry("eventflag", "do_event_flag", POS_DEAD, GM_HIGH_WIZARD),
    entry("geteventflag", "do_get_event_flag", POS_DEAD, GM_LOW_WIZARD),
    entry("item", "do_item", POS_DEAD, GM_GOD),
    entry("mob", "do_mob", POS_DEAD, GM_HIGH_WIZARD),
    entry("mob_ld", "do_mob_ld", POS_DEAD, GM_HIGH_WIZARD),
    entry("ma", "do_mob_aggresive", POS_DEAD, GM_HIGH_WIZARD),
    entry("mc", "do_mob_coward", POS_DEAD, GM_HIGH_WIZARD),
    entry("mm", "do_mob_map", POS_DEAD, GM_HIGH_WIZARD),
    entry("kill", "do_kill", POS_DEAD, GM_HIGH_WIZARD),
    entry("ipurge", "do_item_purge", POS_DEAD, GM_HIGH_WIZARD),
    entry("group", "do_group", POS_DEAD, GM_HIGH_WIZARD),
    entry("grrandom", "do_group_random", POS_DEAD, GM_HIGH_WIZARD),
    entry("set", "do_set", POS_DEAD, GM_IMPLEMENTOR),
    entry("reset", "do_reset", POS_DEAD, GM_HIGH_WIZARD),
    entry("greset", "do_greset", POS_DEAD, GM_HIGH_WIZARD),
    entry("advance", "do_advance", POS_DEAD, GM_GOD),
    entry("book", "do_book", POS_DEAD, GM_IMPLEMENTOR),
    entry("console", "do_console", POS_DEAD, GM_LOW_WIZARD),
    entry("restart_now", "do_restart_now", POS_DEAD, GM_PLAYER),
    entry("shutdow", "do_inputall", POS_DEAD, GM_HIGH_WIZARD),
    entry("shutdown", "do_shutdown", POS_DEAD, GM_HIGH_WIZARD),
    entry("stat", "do_stat", POS_DEAD, GM_PLAYER),
    entry("stat-", "do_stat_minus", POS_DEAD, GM_PLAYER),
    entry("stat_reset", "do_stat_reset", POS_DEAD, GM_LOW_WIZARD),
    entry("state", "do_state", POS_DEAD, GM_LOW_WIZARD),
    entry("stun", "do_stun", POS_DEAD, GM_LOW_WIZARD),
    entry("slow", "do_slow", POS_DEAD, GM_LOW_WIZARD),
    entry("multi_farm", "do_multi_farm", POS_DEAD, GM_PLAYER),
    entry(
        "open_global_rank",
        "do_open_global_rank",
        POS_DEAD,
        GM_PLAYER,
    ),
    entry(
        "rank_end_season",
        "do_global_rank_end_season",
        POS_DEAD,
        GM_IMPLEMENTOR,
    ),
    entry("respawn", "do_respawn", POS_DEAD, GM_WIZARD),
    entry("makeguild", "do_makeguild", POS_DEAD, GM_HIGH_WIZARD),
    entry("deleteguild", "do_deleteguild", POS_DEAD, GM_HIGH_WIZARD),
    entry("mount", "do_mount", POS_MOUNTING, GM_PLAYER),
    entry("restart_here", "do_restart", POS_DEAD, GM_PLAYER),
    entry("restart_town", "do_restart", POS_DEAD, GM_PLAYER),
    entry("phase_selec", "do_inputall", POS_DEAD, GM_PLAYER),
    entry("phase_select", "do_cmd", POS_DEAD, GM_PLAYER),
    entry("qui", "do_inputall", POS_DEAD, GM_PLAYER),
    entry("quit", "do_cmd", POS_DEAD, GM_PLAYER),
    entry("logou", "do_inputall", POS_DEAD, GM_PLAYER),
    entry("logout", "do_cmd", POS_DEAD, GM_PLAYER),
    entry("skillup", "do_skillup", POS_DEAD, GM_PLAYER),
    entry("gskillup", "do_guildskillup", POS_DEAD, GM_PLAYER),
    entry("pvp", "do_pvp", POS_DEAD, GM_PLAYER),
    entry("safebox", "do_safebox_size", POS_DEAD, GM_HIGH_WIZARD),
    entry("safebox_close", "do_safebox_close", POS_DEAD, GM_PLAYER),
    entry("safebox_passwor", "do_inputall", POS_DEAD, GM_PLAYER),
    entry(
        "safebox_password",
        "do_safebox_password",
        POS_DEAD,
        GM_PLAYER,
    ),
    entry("safebox_change_passwor", "do_inputall", POS_DEAD, GM_PLAYER),
    entry(
        "safebox_change_password",
        "do_safebox_change_password",
        POS_DEAD,
        GM_PLAYER,
    ),
    entry("mall_passwor", "do_inputall", POS_DEAD, GM_PLAYER),
    entry("mall_password", "do_mall_password", POS_DEAD, GM_PLAYER),
    entry("mall_close", "do_mall_close", POS_DEAD, GM_PLAYER),
    entry("ungroup", "do_ungroup", POS_DEAD, GM_PLAYER),
    entry("refine_rod", "do_refine_rod", POS_DEAD, GM_IMPLEMENTOR),
    entry("refine_pick", "do_refine_pick", POS_DEAD, GM_IMPLEMENTOR),
    entry("max_pick", "do_max_pick", POS_DEAD, GM_IMPLEMENTOR),
    entry("fish_simul", "do_fishing_simul", POS_DEAD, GM_IMPLEMENTOR),
    entry("invisible", "do_invisibility", POS_DEAD, GM_LOW_WIZARD),
    entry("qf", "do_qf", POS_DEAD, GM_IMPLEMENTOR),
    entry("clear_quest", "do_clear_quest", POS_DEAD, GM_HIGH_WIZARD),
    entry("close_shop", "do_close_shop", POS_DEAD, GM_PLAYER),
    entry("set_walk_mode", "do_set_walk_mode", POS_DEAD, GM_PLAYER),
    entry("set_run_mode", "do_set_run_mode", POS_DEAD, GM_PLAYER),
    entry("setjob", "do_set_skill_group", POS_DEAD, GM_IMPLEMENTOR),
    entry("setskill", "do_setskill", POS_DEAD, GM_LOW_WIZARD),
    entry(
        "setskillother",
        "do_setskillother",
        POS_DEAD,
        GM_HIGH_WIZARD,
    ),
    entry(
        "setskillpoint",
        "do_set_skill_point",
        POS_DEAD,
        GM_IMPLEMENTOR,
    ),
    entry("reload", "do_reload", POS_DEAD, GM_IMPLEMENTOR),
    entry("cooltime", "do_cooltime", POS_DEAD, GM_HIGH_WIZARD),
    entry("gwlist", "do_gwlist", POS_DEAD, GM_LOW_WIZARD),
    entry("gwstop", "do_stop_guild_war", POS_DEAD, GM_LOW_WIZARD),
    entry("gwcancel", "do_cancel_guild_war", POS_DEAD, GM_LOW_WIZARD),
    entry("gstate", "do_guild_state", POS_DEAD, GM_LOW_WIZARD),
    entry("pkmode", "do_pkmode", POS_DEAD, GM_PLAYER),
    entry("messenger_auth", "do_messenger_auth", POS_DEAD, GM_PLAYER),
    entry("getqf", "do_getqf", POS_DEAD, GM_LOW_WIZARD),
    entry("setqf", "do_setqf", POS_DEAD, GM_LOW_WIZARD),
    entry("delqf", "do_delqf", POS_DEAD, GM_LOW_WIZARD),
    entry("set_state", "do_set_state", POS_DEAD, GM_LOW_WIZARD),
    entry("detaillog", "do_detaillog", POS_DEAD, GM_LOW_WIZARD),
    entry("monsterlog", "do_monsterlog", POS_DEAD, GM_LOW_WIZARD),
    entry("forgetme", "do_forgetme", POS_DEAD, GM_LOW_WIZARD),
    entry("aggregate", "do_aggregate", POS_DEAD, GM_LOW_WIZARD),
    entry(
        "attract_ranger",
        "do_attract_ranger",
        POS_DEAD,
        GM_LOW_WIZARD,
    ),
    entry("pull_monster", "do_pull_monster", POS_DEAD, GM_LOW_WIZARD),
    entry("setblockmode", "do_setblockmode", POS_DEAD, GM_PLAYER),
    entry("polymorph", "do_polymorph", POS_DEAD, GM_LOW_WIZARD),
    entry("polyitem", "do_polymorph_item", POS_DEAD, GM_HIGH_WIZARD),
    entry("priv_empire", "do_priv_empire", POS_DEAD, GM_HIGH_WIZARD),
    entry("priv_guild", "do_priv_guild", POS_DEAD, GM_HIGH_WIZARD),
    entry("mount_test", "do_mount_test", POS_DEAD, GM_IMPLEMENTOR),
    entry("unmount", "do_unmount", POS_DEAD, GM_PLAYER),
    entry("private", "do_private", POS_DEAD, GM_IMPLEMENTOR),
    entry("party_request", "do_party_request", POS_DEAD, GM_PLAYER),
    entry(
        "party_request_accept",
        "do_party_request_accept",
        POS_DEAD,
        GM_PLAYER,
    ),
    entry(
        "party_request_deny",
        "do_party_request_deny",
        POS_DEAD,
        GM_PLAYER,
    ),
    entry("observer", "do_observer", POS_DEAD, GM_IMPLEMENTOR),
    entry("observer_exit", "do_observer_exit", POS_DEAD, GM_PLAYER),
    entry("socketitem", "do_socket_item", POS_DEAD, GM_IMPLEMENTOR),
    entry(
        "saveati",
        "do_save_attribute_to_image",
        POS_DEAD,
        GM_IMPLEMENTOR,
    ),
    entry("xmas_boom", "do_xmas", POS_DEAD, GM_HIGH_WIZARD),
    entry("xmas_snow", "do_xmas", POS_DEAD, GM_HIGH_WIZARD),
    entry("xmas_santa", "do_xmas", POS_DEAD, GM_HIGH_WIZARD),
    entry("view_equip", "do_view_equip", POS_DEAD, GM_PLAYER),
    entry("jy", "do_block_chat", POS_DEAD, GM_HIGH_WIZARD),
    entry("vote_block_chat", "do_vote_block_chat", POS_DEAD, GM_PLAYER),
    entry("block_chat", "do_block_chat", POS_DEAD, GM_PLAYER),
    entry("block_chat_list", "do_block_chat_list", POS_DEAD, GM_PLAYER),
    entry("build", "do_build", POS_DEAD, GM_PLAYER),
    entry("clear_land", "do_clear_land", POS_DEAD, GM_HIGH_WIZARD),
    entry("affect_remove", "do_affect_remove", POS_DEAD, GM_LOW_WIZARD),
    entry("horse_state", "do_horse_state", POS_DEAD, GM_HIGH_WIZARD),
    entry("horse_level", "do_horse_level", POS_DEAD, GM_HIGH_WIZARD),
    entry("horse_ride", "do_horse_ride", POS_DEAD, GM_HIGH_WIZARD),
    entry("horse_summon", "do_horse_summon", POS_DEAD, GM_HIGH_WIZARD),
    entry(
        "horse_unsummon",
        "do_horse_unsummon",
        POS_DEAD,
        GM_HIGH_WIZARD,
    ),
    entry(
        "horse_set_stat",
        "do_horse_set_stat",
        POS_DEAD,
        GM_HIGH_WIZARD,
    ),
    entry("emotion_allow", "do_emotion_allow", POS_FIGHTING, GM_PLAYER),
    entry("kiss", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("slap", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("french_kiss", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("clap", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("cheer1", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("cheer2", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("dungeon_info", "do_dungeon_info", POS_DEAD, GM_PLAYER),
    entry("dance1", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("dance2", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("dance3", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("dance4", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("dance5", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("dance6", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("congratulation", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("forgive", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("angry", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("attractive", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("sad", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("shy", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("cheerup", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("banter", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("joy", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("pushup", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("dance7", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("exercise", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("doze", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("selfie", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("cherging", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("nosay", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("weather_1", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("weather_2", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("weather_3", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("hungry", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("siren", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("letter", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("call", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("celebration", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("alcohol", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("busy", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("whirl", "do_emotion", POS_FIGHTING, GM_PLAYER),
    entry("reward_system", "do_reward_system", POS_DEAD, GM_PLAYER),
    entry("change_attr", "do_change_attr", POS_DEAD, GM_IMPLEMENTOR),
    entry("add_attr", "do_add_attr", POS_DEAD, GM_IMPLEMENTOR),
    entry("add_socket", "do_add_socket", POS_DEAD, GM_IMPLEMENTOR),
    entry(
        "user_horse_ride",
        "do_user_horse_ride",
        POS_FISHING,
        GM_PLAYER,
    ),
    entry(
        "user_horse_back",
        "do_user_horse_back",
        POS_FISHING,
        GM_PLAYER,
    ),
    entry(
        "user_horse_feed",
        "do_user_horse_feed",
        POS_FISHING,
        GM_PLAYER,
    ),
    entry(
        "show_arena_list",
        "do_show_arena_list",
        POS_DEAD,
        GM_LOW_WIZARD,
    ),
    entry("end_all_duel", "do_end_all_duel", POS_DEAD, GM_LOW_WIZARD),
    entry("end_duel", "do_end_duel", POS_DEAD, GM_LOW_WIZARD),
    entry("duel", "do_duel", POS_DEAD, GM_LOW_WIZARD),
    entry("con+", "do_stat_plus_amount", POS_DEAD, GM_LOW_WIZARD),
    entry("int+", "do_stat_plus_amount", POS_DEAD, GM_LOW_WIZARD),
    entry("str+", "do_stat_plus_amount", POS_DEAD, GM_LOW_WIZARD),
    entry("dex+", "do_stat_plus_amount", POS_DEAD, GM_LOW_WIZARD),
    entry(
        "break_marriage",
        "do_break_marriage",
        POS_DEAD,
        GM_LOW_WIZARD,
    ),
    entry("show_quiz", "do_oxevent_show_quiz", POS_DEAD, GM_LOW_WIZARD),
    entry("log_oxevent", "do_oxevent_log", POS_DEAD, GM_LOW_WIZARD),
    entry(
        "get_oxevent_att",
        "do_oxevent_get_attender",
        POS_DEAD,
        GM_LOW_WIZARD,
    ),
    entry("effect", "do_effect", POS_DEAD, GM_LOW_WIZARD),
    entry(
        "threeway_info",
        "do_threeway_war_info",
        POS_DEAD,
        GM_LOW_WIZARD,
    ),
    entry(
        "threeway_myinfo",
        "do_threeway_war_myinfo",
        POS_DEAD,
        GM_LOW_WIZARD,
    ),
    entry("mto", "do_monarch_warpto", POS_DEAD, GM_PLAYER),
    entry("mtr", "do_monarch_transfer", POS_DEAD, GM_PLAYER),
    entry("minfo", "do_monarch_info", POS_DEAD, GM_PLAYER),
    entry("mtax", "do_monarch_tax", POS_DEAD, GM_PLAYER),
    entry("mmob", "do_monarch_mob", POS_DEAD, GM_PLAYER),
    entry("elect", "do_elect", POS_DEAD, GM_HIGH_WIZARD),
    entry("rmcandidacy", "do_rmcandidacy", POS_DEAD, GM_LOW_WIZARD),
    entry("setmonarch", "do_setmonarch", POS_DEAD, GM_LOW_WIZARD),
    entry("rmmonarch", "do_rmmonarch", POS_DEAD, GM_LOW_WIZARD),
    entry("hair", "do_hair", POS_DEAD, GM_PLAYER),
    entry("inventory", "do_inventory", POS_DEAD, GM_LOW_WIZARD),
    entry("cube", "do_cube", POS_DEAD, GM_PLAYER),
    entry("cards", "do_cards", POS_DEAD, GM_PLAYER),
    entry("siege", "do_siege", POS_DEAD, GM_LOW_WIZARD),
    entry("temp", "do_temp", POS_DEAD, GM_IMPLEMENTOR),
    entry("frog", "do_frog", POS_DEAD, GM_HIGH_WIZARD),
    entry(
        "check_mmoney",
        "do_check_monarch_money",
        POS_DEAD,
        GM_IMPLEMENTOR,
    ),
    entry(
        "reset_subskill",
        "do_reset_subskill",
        POS_DEAD,
        GM_HIGH_WIZARD,
    ),
    entry("flush", "do_flush", POS_DEAD, GM_IMPLEMENTOR),
    entry("gift", "do_gift", POS_DEAD, GM_PLAYER),
    entry("mnotice", "do_monarch_notice", POS_DEAD, GM_PLAYER),
    entry("eclipse", "do_eclipse", POS_DEAD, GM_HIGH_WIZARD),
    entry("weeklyevent", "do_weeklyevent", POS_DEAD, GM_LOW_WIZARD),
    entry("eventhelper", "do_event_helper", POS_DEAD, GM_HIGH_WIZARD),
    entry("in_game_mall", "do_in_game_mall", POS_DEAD, GM_PLAYER),
    entry("get_mob_count", "do_get_mob_count", POS_DEAD, GM_LOW_WIZARD),
    entry("dice", "do_dice", POS_DEAD, GM_PLAYER),
    entry("special_item", "do_special_item", POS_DEAD, GM_IMPLEMENTOR),
    entry("click_mall", "do_click_mall", POS_DEAD, GM_PLAYER),
    entry("ride", "do_ride", POS_DEAD, GM_PLAYER),
    entry(
        "item_id_list",
        "do_get_item_id_list",
        POS_DEAD,
        GM_LOW_WIZARD,
    ),
    entry("set_socket", "do_set_socket", POS_DEAD, GM_LOW_WIZARD),
    entry("costume", "do_costume", POS_DEAD, GM_PLAYER),
    entry("tcon", "do_set_stat", POS_DEAD, GM_LOW_WIZARD),
    entry("tint", "do_set_stat", POS_DEAD, GM_LOW_WIZARD),
    entry("tstr", "do_set_stat", POS_DEAD, GM_LOW_WIZARD),
    entry("tdex", "do_set_stat", POS_DEAD, GM_LOW_WIZARD),
    entry("cannot_dead", "do_can_dead", POS_DEAD, GM_LOW_WIZARD),
    entry("can_dead", "do_can_dead", POS_DEAD, GM_LOW_WIZARD),
    entry("full_set", "do_full_set", POS_DEAD, GM_LOW_WIZARD),
    entry("item_full_set", "do_item_full_set", POS_DEAD, GM_LOW_WIZARD),
    entry("attr_full_set", "do_attr_full_set", POS_DEAD, GM_LOW_WIZARD),
    entry(
        "all_skill_master",
        "do_all_skill_master",
        POS_DEAD,
        GM_LOW_WIZARD,
    ),
    entry("w_gaya", "do_gaya_system", POS_DEAD, GM_PLAYER),
    entry("use_item", "do_use_item", POS_DEAD, GM_LOW_WIZARD),
    entry("dragon_soul", "do_dragon_soul", POS_DEAD, GM_PLAYER),
    entry("give_reward", "give_reward", POS_DEAD, GM_PLAYER),
    entry("letters_open", "letters_open", POS_DEAD, GM_PLAYER),
    entry("ds_list", "do_ds_list", POS_DEAD, GM_PLAYER),
    entry(
        "do_clear_affect",
        "do_clear_affect",
        POS_DEAD,
        GM_LOW_WIZARD,
    ),
    entry(
        "advance_skill_select",
        "do_advance_skill_select",
        POS_DEAD,
        GM_PLAYER,
    ),
    entry("move_channel", "do_move_channel", POS_DEAD, GM_PLAYER),
    entry("pickup_affect", "do_pickup_affect", POS_DEAD, GM_PLAYER),
    entry("sort_inventory", "do_sort_inventory", POS_DEAD, GM_PLAYER),
    entry("stat_val", "do_stat_val", POS_DEAD, GM_PLAYER),
    entry(
        "daily_gift_event",
        "do_daily_gift_event",
        POS_DEAD,
        GM_IMPLEMENTOR,
    ),
    entry("hide_costume", "do_hide_costume", POS_DEAD, GM_PLAYER),
    entry(
        "do_click_special_inv",
        "do_click_special_inv",
        POS_DEAD,
        GM_PLAYER,
    ),
    entry("conqueror_point", "do_conqueror_point", POS_DEAD, GM_PLAYER),
    entry(
        "conqueror_level",
        "do_conqueror_level",
        POS_DEAD,
        GM_LOW_WIZARD,
    ),
    entry("battle_pass", "do_battle_pass", POS_DEAD, GM_PLAYER),
    entry(
        "battle_pass_admin",
        "do_battle_pass_admin",
        POS_DEAD,
        GM_IMPLEMENTOR,
    ),
    entry(
        "add_rare_attr",
        "do_add_rare_attr",
        POS_DEAD,
        GM_IMPLEMENTOR,
    ),
    entry(
        "change_rare_attr",
        "do_change_rare_attr",
        POS_DEAD,
        GM_IMPLEMENTOR,
    ),
    entry("click_safebox", "do_click_safebox", POS_DEAD, GM_PLAYER),
    entry("force_logout", "do_force_logout", POS_DEAD, GM_IMPLEMENTOR),
    entry("poison", "do_poison", POS_DEAD, GM_IMPLEMENTOR),
    entry("rewarp", "do_rewarp", POS_DEAD, GM_LOW_WIZARD),
    entry(
        "fetch_casket_items",
        "do_fetch_casket_items",
        POS_DEAD,
        GM_PLAYER,
    ),
    entry("worldboss", "do_worldboss", POS_DEAD, GM_IMPLEMENTOR),
];
