[package]
name = "net"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Metin2 client networking layer"

[features]
default = ["tokio"]
tokio = ["dep:tokio"]

[dependencies]
tokio = { workspace = true, optional = true }
tracing = { workspace = true }
protocol = { path = "../protocol" }

[lints]
workspace = true
